/* chain-analysis-experience-v58 */
(function(){
  var selectedCompaniesV58=new Set(),addedCompaniesV58=new Set(),reportCompaniesV58=[];
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function selectedChainV58(){return typeof chainIndustryData!=='undefined'&&chainIndustryData[activeChainKey]?chainIndustryData[activeChainKey]:chainIndustryData.newenergy}
  function patentRankingV58(){
    var cards=Array.from(document.querySelectorAll('#dashboard .ranking-card')),card=cards.find(function(x){return/科创|科技创新/.test(x.textContent)});if(!card)return;
    card.classList.add('innovation-ranking-v58');var title=card.querySelector('h2'),sub=card.querySelector('.card-title p');if(title)title.textContent='企业创新榜';if(sub)sub.textContent='按近半年新增授权专利数量排序 · 单位：项';
    var values=[['126','近半年新增发明专利 68 项'],['112','近半年新增发明专利 54 项'],['96','近半年新增发明专利 47 项'],['83','近半年新增发明专利 39 项'],['71','近半年新增发明专利 32 项']];
    card.querySelectorAll('.rank-row strong').forEach(function(el,i){if(values[i])el.innerHTML=values[i][0]+'<em>'+values[i][1]+'</em>'});
  }
  function updateAnnotationsV58(){
    if(typeof prototypeLogicAnnotations==='undefined')return;
    var dashboard=prototypeLogicAnnotations.dashboard&&prototypeLogicAnnotations.dashboard.fields||[],rank=dashboard.find(function(x){return/纳税与科技创新榜|创新榜|专利榜/.test(x[0])});if(rank){rank[0]='纳税与企业创新榜';rank[1]='纳税榜按本年度累计实缴税额排序；企业创新榜按企业近半年新增授权专利数量从高到低排序。';rank[2]='税务汇总数据、国家知识产权授权数据、企业统一社会信用代码';rank[3]='专利数据每日更新，榜单按月固化'}
    var chain=prototypeLogicAnnotations.chain&&prototypeLogicAnnotations.chain.fields||[],rate=chain.find(function(x){return x[0]==='本地配套率'});if(rate){rate[1]='大白话理解：本地产业链一共需要多少关键原料、零部件和服务，其中有多少能由海州市本地企业提供。比如本地企业总共需要100万元的配套产品，本地供应商能提供64万元，本地配套率就是64%。';rate[2]='本地企业采购需求、供应商产品清单、供需关系和可供货能力';rate[3]='月度更新，重大项目投产或企业供需变化后重算'}
    if(prototypeLogicAnnotations.investment){prototypeLogicAnnotations.investment.interactions.push(['单节点强链补链分析','点击产业链单个节点。','直接弹出该节点推荐企业清单，每家企业可加入招商名单，不生成重型报告。'],['产业链整体分析','点击页面级强链补链分析推荐。','进入招商线索雷达二级报告页面，支持面包屑返回；推荐企业可单个或批量加入招商名单。'])}
  }
  function renderSingleNodeV58(name){
    currentNodeCompanyName=name;var modal=document.getElementById('nodeCompanyModal'),dialog=modal&&modal.querySelector('.node-company-modal');if(!modal||!dialog)return;
    dialog.classList.add('single-node-recommend-v58');document.getElementById('nodeCompanyTitle').textContent=name+' · 强链补链推荐企业';var desc=dialog.querySelector('header p');if(desc)desc.textContent='AI 已围绕“'+name+'”节点完成全国企业召回与精排，以下企业可补齐本地关键能力';
    var companies=nodeExternalCompanies.slice().sort(function(a,b){return b.score-a.score}).slice(0,10),high=companies.filter(function(x){return x.score>=90}).length,signal=companies.filter(function(x){return x.signalStrong}).length;
    document.getElementById('nodeCompanySummary').innerHTML='<span class="metric-static"><span>推荐企业</span><b>'+companies.length+' 家</b></span><span class="metric-static"><span>高潜目标</span><b>'+high+' 家</b></span><span class="metric-static"><span>近期扩张信号</span><b>'+signal+' 家</b></span>';
    document.getElementById('nodeCompanyTableHead').innerHTML='<tr><th>推荐企业</th><th>所在地区</th><th>补链能力</th><th>近期投资信号</th><th>匹配度</th><th>操作</th></tr>';
    document.getElementById('nodeCompanyRows').innerHTML=companies.map(function(x,i){var tags=x.tags||['待核验'],encoded=encodeURIComponent(x.name),match=Math.max(82,Number(x.score||88)-Math.floor(i/4));return'<tr><td><b>'+esc(x.name)+'</b><span class="node-recommend-badge-v58">'+esc(tags[0])+'</span></td><td>'+esc(String(x.loc||'全国').split(' · ')[0])+'</td><td><span class="node-overflow" title="'+esc(name+'关键能力补位')+'">'+esc(name)+'关键能力补位</span></td><td><span class="signal node-overflow" title="'+esc(x.signal||'持续跟踪')+'">↑ '+esc(x.signal||'持续跟踪')+'</span></td><td><b style="color:#1c71df">'+match+'%</b></td><td><div class="node-actions"><button class="node-add-btn-v58" onclick="addNodeCompanyV58(decodeURIComponent(\''+encoded+'\'),this)">＋ 加入招商名单</button></div></td></tr>'}).join('');
    var note=document.getElementById('nodeModalNote');if(note)note.textContent='推荐结果按节点相关度、扩张意愿、风险合规、创新与经营能力综合排序';var more=document.getElementById('nodeMoreFilterBtn');if(more)more.style.display='none';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';
  }
  openNodeCompanyList=renderSingleNodeV58;
  window.openNodeCompanyList=renderSingleNodeV58;  var chainFlowV58=document.getElementById('chainFlow');
  if(chainFlowV58)chainFlowV58.addEventListener('click',function(event){var button=event.target.closest('.chain-node');if(!button)return;event.preventDefault();event.stopImmediatePropagation();chainFlowV58.querySelectorAll('.chain-node').forEach(function(x){x.classList.remove('selected')});button.classList.add('selected');renderSingleNodeV58(button.dataset.chain)},true);
  window.addNodeCompanyV58=function(name,button){addInvestmentTarget(name);button.textContent='✓ 已加入';button.disabled=true;button.classList.add('added')};
  function ensureReportViewV58(){
    if(document.getElementById('chainReportV58'))return;
    var main=document.querySelector('main.main');if(!main)return;
    var section=document.createElement('section');section.className='content view chain-report-view-v58';section.id='chainReportV58';section.innerHTML='<div class="chain-report-back-v58"><button type="button" onclick="returnToInvestmentV58()">‹ 返回招商线索雷达</button><span>招商线索雷达 / 产业链整体分析报告</span></div><div class="chain-report-head-v58"><div><label>AI INDUSTRY CHAIN REPORT</label><h1 id="chainReportTitleV58">产业链强链补链整体分析报告</h1><p id="chainReportMetaV58">AI 产业链分析师 · 数据更新至今日 08:00</p></div><div class="report-actions-v58"><button class="secondary" onclick="window.print()">打印报告</button><button class="primary" onclick="toast(\'报告已加入产业决策专报\')">加入决策专报</button></div></div><div class="chain-report-kpis-v58" id="chainReportKpisV58"></div><div class="chain-report-grid-v58"><section class="card chain-report-section-v58"><header><h2>核心量化判断</h2><span>基于海州市产业链图谱与企业供需关系</span></header><p class="chain-report-summary-v58" id="chainReportSummaryV58"></p></section><section class="chain-report-judgements-v58" id="chainReportJudgementsV58"></section></div><section class="card chain-report-section-v58" style="margin-bottom:14px"><header><h2>关键薄弱环节与补链方向</h2><span>按紧迫度与产业带动价值排序</span></header><div class="gap-cards-v58" id="chainReportGapsV58"></div></section><section class="card chain-report-recommend-v58"><header><div><h2>招商推荐企业名单</h2><p>按产业补位价值与招商评估模型综合得分倒序展示</p></div><div class="chain-report-batch-v58"><label><input id="chainReportSelectAllV58" type="checkbox" onchange="selectAllChainReportV58(this.checked)"> 全选</label><span id="chainReportSelectedCountV58">已选 0 家</span><button class="primary" onclick="batchAddChainReportV58()">批量加入招商名单</button></div></header><div class="chain-report-table-wrap-v58"><table class="chain-report-table-v58"><thead><tr><th></th><th>推荐企业</th><th>所在地区</th><th>主要补链方向</th><th>近期扩张信号</th><th>匹配度</th><th>操作</th></tr></thead><tbody id="chainReportRowsV58"></tbody></table></div></section><section class="card chain-report-section-v58"><header><h2>分阶段行动建议</h2><span>从线索到落地的任务闭环</span></header><div class="chain-report-roadmap-v58"><article><b>第一阶段：名单核验</b><span>0—30 天</span><p>核验企业主体、扩张信号和关键产品能力，形成首批重点接洽清单。</p></article><article><b>第二阶段：精准接洽</b><span>31—90 天</span><p>开展企业尽调、链主供需验证与落地要素匹配，形成“一企一策”。</p></article><article><b>第三阶段：落地跟踪</b><span>3—12 个月</span><p>跟踪签约、开工、投产与达效，按季度重算链条完备度和本地配套率。</p></article></div></section>';
    main.appendChild(section);if(typeof names!=='undefined')names.chainReportV58='产业链整体分析报告';
  }
  function renderReportRowsV58(){var rows=document.getElementById('chainReportRowsV58');if(!rows)return;var d=selectedChainV58(),directions=(d.gaps||[]).map(function(x){return x[0]});rows.innerHTML=reportCompaniesV58.map(function(x,i){var encoded=encodeURIComponent(x.name),checked=selectedCompaniesV58.has(x.name)?' checked':'',added=addedCompaniesV58.has(x.name),direction=directions[i%directions.length]||'关键能力补位';return'<tr><td><input type="checkbox" data-report-company="'+esc(x.name)+'" onchange="toggleChainReportCompanyV58(decodeURIComponent(\''+encoded+'\'),this.checked)"'+checked+'></td><td><b>'+esc(x.name)+'</b><small>'+esc((x.tags||['重点招商目标'])[0])+'</small></td><td>'+esc(String(x.loc||'全国').split(' · ')[0])+'</td><td><span class="node-recommend-badge-v58">'+esc(direction)+'</span></td><td>'+esc(x.signal||'持续跟踪投资信号')+'</td><td><b class="fit-v58">'+Math.max(82,Number(x.score||88)-Math.floor(i/4))+'%</b></td><td><button class="'+(added?'added':'')+'" '+(added?'disabled':'')+' onclick="addChainReportCompanyV58(decodeURIComponent(\''+encoded+'\'),this)">'+(added?'✓ 已加入':'＋ 加入招商名单')+'</button></td></tr>'}).join('');updateSelectedCountV58()}
  function updateSelectedCountV58(){var count=document.getElementById('chainReportSelectedCountV58');if(count)count.textContent='已选 '+selectedCompaniesV58.size+' 家';var all=document.getElementById('chainReportSelectAllV58');if(all)all.checked=reportCompaniesV58.length>0&&selectedCompaniesV58.size===reportCompaniesV58.length}
  window.toggleChainReportCompanyV58=function(name,checked){if(checked)selectedCompaniesV58.add(name);else selectedCompaniesV58.delete(name);updateSelectedCountV58()};
  window.selectAllChainReportV58=function(checked){selectedCompaniesV58.clear();if(checked)reportCompaniesV58.forEach(function(x){selectedCompaniesV58.add(x.name)});renderReportRowsV58()};
  window.addChainReportCompanyV58=function(name,button){addInvestmentTarget(name);addedCompaniesV58.add(name);button.textContent='✓ 已加入';button.disabled=true;button.classList.add('added')};
  window.batchAddChainReportV58=function(){if(!selectedCompaniesV58.size){toast('请先勾选需要加入的企业');return}selectedCompaniesV58.forEach(function(name){addInvestmentTarget(name);addedCompaniesV58.add(name)});toast('已批量加入 '+selectedCompaniesV58.size+' 家企业至招商名单');renderReportRowsV58()};
  window.returnToInvestmentV58=function(){show('investment');document.querySelectorAll('.nav[data-view]').forEach(function(x){x.classList.toggle('active',x.dataset.view==='investment')})};
  window.openWholeChainReportV58=function(){
    ensureReportViewV58();var d=selectedChainV58(),weak=(d.gaps||[]).length||d.weak||0;selectedCompaniesV58.clear();reportCompaniesV58=nodeExternalCompanies.slice().sort(function(a,b){return b.score-a.score}).slice(0,12);
    document.getElementById('chainReportTitleV58').textContent='海州市'+d.name+'强链补链整体分析报告';document.getElementById('chainReportMetaV58').textContent='AI 产业链分析师 · '+d.companies+' 家链上企业 · 数据更新至 '+new Date().toLocaleDateString('zh-CN');
    document.getElementById('chainReportKpisV58').innerHTML=[['链上企业',d.companies+' 家','企业统一社会信用代码去重'],['链条完备度',d.complete+'%','目标必备节点覆盖程度'],['本地配套率',d.local+'%','本地需求中由本地企业满足的比例'],['关键薄弱节点',weak+' 个','建议优先补链'],['产业综合得分',d.score,'本地产业家底综合研判']].map(function(x){return'<article class="card"><span>'+x[0]+'</span><b>'+x[1]+'</b><em>'+x[2]+'</em></article>'}).join('');
    document.getElementById('chainReportSummaryV58').innerHTML='海州市'+esc(d.name)+'已形成一定产业集聚基础，链条完备度为 <b>'+d.complete+'%</b>，本地配套率为 <b>'+d.local+'%</b>。'+esc(d.summary)+' 建议采取“本地企业培育、薄弱节点招引、公共平台补齐”三条路径同步推进。';
    document.getElementById('chainReportJudgementsV58').innerHTML='<article class="card"><b>现有优势</b><span>链主企业和核心制造环节已形成规模，可向上下游开放采购与应用场景。</span></article><article class="card"><b>首要短板</b><span>关键输入品、核心零部件及专业服务仍依赖外部供应，影响产业韧性。</span></article><article class="card"><b>招商策略</b><span>优先对接高相关、强扩张、低风险企业，并同步核验海州市承载条件。</span></article>';
    document.getElementById('chainReportGapsV58').innerHTML=(d.gaps||[]).slice(0,3).map(function(g,i){return'<article class="gap-card-v58"><span>优先级 '+(i+1)+'</span><b>'+esc(g[0])+'</b><p>'+esc(g[2])+'。'+esc(g[4])+'。</p><em>'+esc(g[3])+'</em></article>'}).join('');renderReportRowsV58();show('chainReportV58');document.getElementById('crumb').textContent='产业链整体分析报告';document.querySelectorAll('.nav[data-view]').forEach(function(x){x.classList.toggle('active',x.dataset.view==='investment')});window.scrollTo({top:0,behavior:'smooth'});
  };
  ensureReportViewV58();var mainButton=document.querySelector('.radar-recommend-btn');if(mainButton){mainButton.textContent='强链补链分析推荐';mainButton.onclick=window.openWholeChainReportV58}
  patentRankingV58();updateAnnotationsV58();
})();