/* node-local-and-recommendation-flow-v59 */
(function(){
  var activeNodeV59='车规级芯片';
  function escV59(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})}
  function localAbilityV59(company,node,index){if(node==='车规级芯片')return company.ability;var roles=['核心产品供给','关键零部件配套','链主应用验证','制造装备协同','数字化服务支撑','上游材料保障','公共检测认证','核心工艺协同','规模化生产协同','供应链服务保障'];return node+' · '+roles[index%roles.length]}
  function renderLocalCompaniesV59(node){
    var modal=document.getElementById('nodeCompanyModal'),dialog=modal&&modal.querySelector('.node-company-modal');if(!modal||!dialog)return;
    activeNodeV59=node;currentNodeCompanyName=node;dialog.classList.remove('single-node-recommend-v58');dialog.classList.add('node-two-phase-v59','node-local-stage-v59');
    document.getElementById('nodeCompanyTitle').textContent=node+' · 本地挂靠企业';var description=dialog.querySelector('header>div>p');if(description)description.textContent='先核验本地企业挂靠关系与节点能力，再启动 AI 节点补强分析，形成外地招商推荐清单';
    var aiBrief=dialog.querySelector('.node-ai-brief');if(aiBrief)aiBrief.style.display='flex';var insight=document.getElementById('nodeCompanyAiSummary');if(insight)insight.textContent=getNodeAiSummary(node);
    var companies=nodeLocalCompanies.slice(),keyCount=companies.filter(function(x){return x.fit>=88}).length,avg=Math.round(companies.reduce(function(sum,x){return sum+x.fit},0)/companies.length);
    document.getElementById('nodeCompanySummary').innerHTML='<span class="metric-static"><span>本地挂靠企业</span><b>'+companies.length+' 家</b></span><span class="metric-static"><span>链主及重点企业</span><b>'+keyCount+' 家</b></span><span class="metric-static"><span>平均协同度</span><b>'+avg+'%</b></span>';
    document.getElementById('nodeCompanyTableHead').innerHTML='<tr><th>本地挂靠企业</th><th>所在园区</th><th>节点角色</th><th>节点挂靠能力</th><th>协同度</th><th>操作</th></tr>';
    document.getElementById('nodeCompanyRows').innerHTML=companies.map(function(company,index){var ability=localAbilityV59(company,node,index);return'<tr><td><b>'+escV59(company.name)+'</b><span>'+escV59((company.tags||[]).slice(0,2).join(' / '))+'</span></td><td>'+escV59(company.park)+'</td><td><span class="node-overflow" title="'+escV59(company.role)+'">'+escV59(company.role)+'</span></td><td><span class="node-overflow" title="'+escV59(ability)+'">'+escV59(ability)+'</span></td><td><b class="local-fit-v59">'+company.fit+'%</b></td><td><button class="node-profile-btn-v59" onclick="toast(\'正在打开'+escV59(company.name)+'企业画像\')">查看企业画像</button></td></tr>'}).join('');
    var note=document.getElementById('nodeModalNote');if(note)note.textContent='本地挂靠企业由企业主营产品、产业链节点标签和业务关联强度综合识别，可在产业链库中校正挂靠关系';var action=document.getElementById('nodeMoreFilterBtn');if(action){action.style.display='inline-flex';action.disabled=false;action.className='primary node-reinforce-btn-v59';action.textContent='✦ 节点补强分析与推荐';action.onclick=runNodeReinforceV59}
    modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';
  }
  function renderRecommendedCompaniesV59(){
    var dialog=document.querySelector('#nodeCompanyModal .node-company-modal');if(!dialog)return;dialog.classList.remove('node-local-stage-v59');dialog.classList.add('node-recommend-stage-v59');document.getElementById('nodeCompanyTitle').textContent=activeNodeV59+' · 节点补强推荐企业';
    var description=dialog.querySelector('header>div>p');if(description)description.textContent='AI 已根据本地节点缺口、产业补位价值、扩张意愿与风险合规完成全国企业召回和精排';var insight=document.getElementById('nodeCompanyAiSummary');if(insight)insight.textContent='本地已具备部分配套和应用基础，当前补强重点是提升核心技术供给、规模化量产与链主协同能力。建议优先接洽以下高匹配企业，并同步核验投资计划与落地条件。';
    var companies=nodeExternalCompanies.slice().sort(function(a,b){return b.score-a.score}).slice(0,10),high=companies.filter(function(x){return x.score>=90}).length,signal=companies.filter(function(x){return x.signalStrong}).length;document.getElementById('nodeCompanySummary').innerHTML='<span class="metric-static"><span>推荐企业</span><b>'+companies.length+' 家</b></span><span class="metric-static"><span>高潜招商目标</span><b>'+high+' 家</b></span><span class="metric-static"><span>近期扩张信号</span><b>'+signal+' 家</b></span>';
    document.getElementById('nodeCompanyTableHead').innerHTML='<tr><th>推荐企业</th><th>所在地区</th><th>主要补强能力</th><th>近期投资信号</th><th>匹配度</th><th>操作</th></tr>';document.getElementById('nodeCompanyRows').innerHTML=companies.map(function(company,index){var encoded=encodeURIComponent(company.name),match=Math.max(82,Number(company.score||88)-Math.floor(index/4));return'<tr><td><b>'+escV59(company.name)+'</b><span>'+escV59((company.tags||['待核验'])[0])+'</span></td><td>'+escV59(String(company.loc||'全国').split(' · ')[0])+'</td><td><span class="node-overflow" title="'+escV59(activeNodeV59+'关键能力补位')+'">'+escV59(activeNodeV59)+'关键能力补位</span></td><td><span class="signal node-overflow" title="'+escV59(company.signal||'持续跟踪')+'">↑ '+escV59(company.signal||'持续跟踪')+'</span></td><td><b class="recommend-fit-v59">'+match+'%</b></td><td><button class="node-add-btn-v59" onclick="addNodeCompanyV59(decodeURIComponent(\''+encoded+'\'),this)">＋ 加入招商名单</button></td></tr>'}).join('');
    var note=document.getElementById('nodeModalNote');if(note)note.textContent='推荐结果按节点相关度、扩张意愿度、风险合规度、技术创新力与财务营收能力综合排序';var action=document.getElementById('nodeMoreFilterBtn');if(action){action.disabled=false;action.className='secondary node-back-local-v59';action.textContent='← 返回本地挂靠企业';action.onclick=function(){renderLocalCompaniesV59(activeNodeV59)}}
  }
  window.runNodeReinforceV59=function(){var action=document.getElementById('nodeMoreFilterBtn');if(!action)return;action.disabled=true;action.textContent='AI 正在分析节点缺口…';var note=document.getElementById('nodeModalNote');if(note)note.textContent='正在结合本地挂靠企业、节点供需缺口、全国企业能力与近期投资信号进行召回和精排';setTimeout(function(){renderRecommendedCompaniesV59();toast('已完成“'+activeNodeV59+'”节点补强分析，推荐 10 家高潜企业')},800)};
  window.addNodeCompanyV59=function(name,button){addInvestmentTarget(name);button.textContent='✓ 已加入';button.disabled=true;button.classList.add('added')};window.openNodeCompanyList=renderLocalCompaniesV59;
  document.addEventListener('click',function(event){var button=event.target.closest&&event.target.closest('#chainFlow .chain-node');if(!button)return;event.preventDefault();event.stopImmediatePropagation();document.querySelectorAll('#chainFlow .chain-node').forEach(function(x){x.classList.remove('selected')});button.classList.add('selected');renderLocalCompaniesV59(button.dataset.chain)},true);
})();
