/* rich-chain-report-v60 */
(function(){
  function escV60(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})}
  function ensureRichReportV60(){
    var report=document.getElementById('chainReportV58'),recommend=report&&report.querySelector('.chain-report-recommend-v58');if(!report||!recommend||document.getElementById('chainStructureV60'))return;
    var structure=document.createElement('section');structure.className='card chain-report-section-v58 rich-report-section-v60';structure.id='chainStructureV60';structure.innerHTML='<header><div><h2>产业基础与结构诊断</h2><p>从企业梯度、空间集聚、创新能力和供需协同四个维度识别产业家底</p></div><span>STRUCTURE DIAGNOSIS</span></header><div class="structure-diagnosis-v60" id="structureDiagnosisV60"></div>';
    var transmission=document.createElement('section');transmission.className='card chain-report-section-v58 rich-report-section-v60';transmission.id='chainTransmissionV60';transmission.innerHTML='<header><div><h2>供需传导与关键缺口量化</h2><p>定位缺口对本地产业链成本、交付、安全和创新的影响路径</p></div><span>GAP TRANSMISSION</span></header><div class="transmission-path-v60" id="transmissionPathV60"></div><div class="gap-table-wrap-v60"><table><thead><tr><th>关键缺口</th><th>本地现状</th><th>影响链路</th><th>风险等级</th><th>建议补强方式</th></tr></thead><tbody id="richGapRowsV60"></tbody></table></div>';
    var strategy=document.createElement('section');strategy.className='card chain-report-section-v58 rich-report-section-v60';strategy.id='chainStrategyV60';strategy.innerHTML='<header><div><h2>招商策略与项目落地条件</h2><p>将产业缺口转化为目标企业画像、承载条件和接洽话术</p></div><span>ATTRACTION STRATEGY</span></header><div class="strategy-grid-v60" id="strategyGridV60"></div>';
    var risk=document.createElement('section');risk.className='card chain-report-section-v58 rich-report-section-v60';risk.id='chainRiskV60';risk.innerHTML='<header><div><h2>实施风险与跟踪指标</h2><p>对推荐有效性、项目落地条件和实施过程设置验证闭环</p></div><span>RISK &amp; KPI</span></header><div class="risk-kpi-grid-v60" id="riskKpiGridV60"></div>';
    recommend.parentNode.insertBefore(structure,recommend);recommend.parentNode.insertBefore(transmission,recommend);recommend.parentNode.insertBefore(strategy,recommend.nextSibling);strategy.parentNode.insertBefore(risk,strategy.nextSibling);
  }
  function fillRichReportV60(){
    ensureRichReportV60();var data=chainIndustryData[activeChainKey]||chainIndustryData.newenergy,gaps=data.gaps||[],topGap=gaps[0]||['关键环节','待测算','存在外部依赖','中风险','定向招引'];
    document.getElementById('structureDiagnosisV60').innerHTML=[['企业梯度','链上企业 '+data.companies+' 家','已形成链主、专精特新与配套企业梯度，但薄弱环节企业密度仍偏低。'],['空间集聚','核心园区承载','建议围绕现有链主企业 30 分钟供应半径优化项目选址和公共服务。'],['创新能力','产业得分 '+data.score,'强项集中于应用和制造环节，关键基础技术与共性平台需要加强。'],['供需协同','本地配套率 '+data.local+'%','仍有 '+(100-data.local).toFixed(1)+'% 的关键需求依赖外部供给，存在招商补位空间。']].map(function(x,i){return'<article><i>0'+(i+1)+'</i><span>'+x[0]+'</span><b>'+x[1]+'</b><p>'+x[2]+'</p></article>'}).join('');
    document.getElementById('transmissionPathV60').innerHTML='<span>关键能力缺口</span><b>→</b><span>外部采购依赖</span><b>→</b><span>成本与交付波动</span><b>→</b><span>链主扩产受限</span><b>→</b><span>产业竞争力下降</span>';document.getElementById('richGapRowsV60').innerHTML=gaps.map(function(g){return'<tr><td><b>'+escV60(g[0])+'</b></td><td>'+escV60(g[1])+'</td><td>'+escV60(g[2])+'</td><td><em class="'+(g[3]==='高风险'?'high':'medium')+'">'+escV60(g[3])+'</em></td><td>'+escV60(g[4])+'</td></tr>'}).join('');
    document.getElementById('strategyGridV60').innerHTML='<article><span>目标企业画像</span><b>'+escV60(topGap[0])+'领域成长型或龙头企业</b><p>具备量产客户、核心专利和异地扩产信号，重大合规风险可控。</p></article><article><span>核心承载条件</span><b>空间、人才、供应链与应用场景协同</b><p>优先提供靠近链主的产业空间、专业人才政策及首批次应用验证机会。</p></article><article><span>重点接洽话术</span><b>以本地市场和链主订单换取关键能力落地</b><p>突出海州市产业规模、客户资源、政策兑现和项目全生命周期服务。</p></article><article><span>项目推进机制</span><b>一企一策 + 周跟踪 + 月研判</b><p>招商、园区、产业部门联合负责，形成尽调、洽谈、签约和投产闭环。</p></article>';
    document.getElementById('riskKpiGridV60').innerHTML=[['推荐有效性','目标企业人工核验通过率 ≥ 70%','以企业主营产品、客户案例和扩张信号交叉核验'],['招商转化','推荐企业有效接洽率 ≥ 30%','跟踪联系人建立、到访考察和投资意向三个阶段'],['落地适配','承载要素满足率 ≥ 80%','核验用地、能耗、人才、资金和上下游配套条件'],['补链成效','关键节点覆盖率逐季提升','项目签约后持续跟踪开工、投产、产值和本地采购额']].map(function(x){return'<article><span>'+x[0]+'</span><b>'+x[1]+'</b><p>'+x[2]+'</p></article>'}).join('');
  }
  var originalV60=window.openWholeChainReportV58;if(originalV60){window.openWholeChainReportV58=function(){originalV60();fillRichReportV60()};var button=document.querySelector('.radar-recommend-btn');if(button)button.onclick=window.openWholeChainReportV58}ensureRichReportV60();
})();
