/* attraction-preference-and-chain-canvas-v63 */
(function(){
  function escV63(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})}
  function setOptionsV63(select,values){if(!select)return;select.innerHTML=values.map(function(value){return'<option>'+escV63(value)+'</option>'}).join('')}
  function patchNodeFilterV63(){
    var title=document.getElementById('nodeFilterTitleV61');if(!title)return;title.textContent='招商补强企业偏好';
    var subtitle=title.parentElement&&title.parentElement.querySelector('p');if(subtitle)subtitle.textContent='设置目标企业偏好后，AI 将结合产业链节点缺口、企业能力与近期扩张信号生成招商推荐名单';
    var region=document.getElementById('nodeFilterRegionV61'),stage=document.getElementById('nodeFilterStageV61'),scale=document.getElementById('nodeFilterScaleV61'),honor=document.getElementById('nodeFilterHonorV61');
    if(region&&region.closest('label'))region.closest('label').querySelector('span').textContent='外招重点地区';
    setOptionsV63(region,['全国','北京市','上海市','广州市','深圳市','杭州市','长三角','粤港澳大湾区','京津冀','中西部地区']);
    if(stage&&stage.closest('label'))stage.closest('label').querySelector('span').textContent='企业阶段';setOptionsV63(stage,['种子期','成长期','成熟期']);
    if(scale&&scale.closest('label'))scale.closest('label').querySelector('span').textContent='企业规模';setOptionsV63(scale,['小微企业','中型企业','大型企业','上市公司']);
    setOptionsV63(honor,['不限','专精特新小巨人','制造业单项冠军','国家高新技术企业']);
  }
  var previousOpenFilterV63=window.openNodeFilterV61;if(previousOpenFilterV63)window.openNodeFilterV61=function(){var result=previousOpenFilterV63.apply(this,arguments);patchNodeFilterV63();return result};
  window.addCultivationCompanyV63=function(name,button){if(button){button.textContent='✓ 已加入培育名单';button.disabled=true;button.classList.add('added')}if(typeof toast==='function')toast('“'+name+'”已加入本地企业培育名单')};
  function patchNodeCompanyActionsV63(){var title=document.getElementById('nodeCompanyTitle'),rows=document.getElementById('nodeCompanyRows');if(!title||!rows)return;var local=title.textContent.indexOf('本地挂靠企业')>-1;if(local){rows.querySelectorAll('tr').forEach(function(row){var button=row.querySelector('.node-profile-btn-v59')||Array.from(row.querySelectorAll('button')).find(function(item){return item.textContent.trim()==='查看企业画像'});if(!button)return;var name=row.querySelector('td:first-child b')?.textContent.trim()||'当前企业';var label=button.textContent.trim();if(label!=='＋ 加入培育名单'&&label.indexOf('已加入')<0)button.textContent='＋ 加入培育名单';button.classList.add('node-cultivate-btn-v63');button.onclick=function(){addCultivationCompanyV63(name,button)}})}else rows.querySelectorAll('.node-add-btn-v59').forEach(function(button){button.classList.add('node-investment-btn-v63')})}
  var nodeRowsV63=document.getElementById('nodeCompanyRows'),nodeModalV63=document.getElementById('nodeCompanyModal');if(nodeRowsV63)new MutationObserver(patchNodeCompanyActionsV63).observe(nodeRowsV63,{childList:true,subtree:true});if(nodeModalV63)new MutationObserver(patchNodeCompanyActionsV63).observe(nodeModalV63,{attributes:true,attributeFilter:['class']});
  function hideRemovedReportModulesV63(){['chainStructureV60','chainTransmissionV60'].forEach(function(id){var section=document.getElementById(id);if(section){section.hidden=true;section.setAttribute('aria-hidden','true')}})}hideRemovedReportModulesV63();
  var previousWholeReportV63=window.openWholeChainReportV58;if(previousWholeReportV63)window.openWholeChainReportV58=function(){var result=previousWholeReportV63.apply(this,arguments);hideRemovedReportModulesV63();return result};
  function nodeHtmlV63(node){return'<button class="chain-node '+escV63(node[2]||'')+'" data-chain="'+escV63(node[0])+'"><b>'+escV63(node[0])+'</b><span>'+escV63(node[1])+'</span>'+(node[3]?'<em class="'+(String(node[2]||'').indexOf('weak')>-1?'':'normal')+'">'+escV63(node[3])+'</em>':'')+'</button>'}
  window.renderIndustryGraph=function(key){var data=chainIndustryData[key];if(!data)return;activeChainKey=key;document.getElementById('chainIndustryTitle').textContent=data.name;document.getElementById('chainIndustryPath').textContent=data.path;document.getElementById('chainCompanyCount').textContent=data.companies+' 家';document.getElementById('chainCompleteness').textContent=data.complete+'%';document.getElementById('chainLocalRate').textContent=data.local+'%';document.getElementById('chainWeakCount').textContent=data.weak+' 个';var service=data.columns.find(function(column){return column.label.indexOf('配套服务')>-1}),main=data.columns.filter(function(column){return column!==service}).slice(0,3);var mainHtml=main.map(function(column,index){return(index?'<div class="chain-arrow">›</div>':'')+'<div class="chain-column"><label>'+escV63(column.label)+'</label>'+column.nodes.map(nodeHtmlV63).join('')+'</div>'}).join('');var serviceHtml=service?'<section class="chain-service-band-v63"><header><div><b>配套服务</b><span>面向上游、中游、下游提供共性支撑</span></div><div class="service-links-v63"><span>支撑上游</span><span>赋能中游</span><span>服务下游</span></div></header><div class="chain-service-nodes-v63">'+service.nodes.map(nodeHtmlV63).join('')+'</div></section>':'';var flow=document.getElementById('chainFlow');flow.innerHTML='<div class="chain-main-v63">'+mainHtml+'</div>'+serviceHtml;flow.querySelectorAll('.chain-node').forEach(function(button){button.onclick=function(){flow.querySelectorAll('.chain-node').forEach(function(item){item.classList.remove('selected')});button.classList.add('selected');openNodeCompanyList(button.dataset.chain)}});var selected=flow.querySelector('.chain-node.selected')||flow.querySelector('.chain-node');if(selected)selected.classList.add('selected')};
  if(typeof activeChainKey!=='undefined'&&typeof chainIndustryData!=='undefined')renderIndustryGraph(activeChainKey);
  var graphEditIndexV63=null;
  function ensureGraphBuilderToolsV63(){var head=document.querySelector('#graphBuilderModal .graph-preview-head');if(head&&!document.getElementById('graphAddNodeBtnV63')){var actions=document.createElement('div');actions.className='graph-preview-actions-v63';actions.innerHTML='<button type="button" id="graphAddNodeBtnV63" onclick="openNewGraphNodeV63()">＋ 新增节点</button>';head.appendChild(actions)}['manualGraphType','graphNodeTypeV47'].forEach(function(id){var select=document.getElementById(id);if(select&&!Array.from(select.options).some(function(option){return option.textContent.trim()==='配套服务'})){var option=document.createElement('option');option.value='配套服务';option.textContent='配套服务';select.appendChild(option)}})}
  window.openNewGraphNodeV63=function(){ensureGraphBuilderToolsV63();graphEditIndexV63=null;document.getElementById('graphNodeEditTitleV47').textContent='新增产业链节点';document.getElementById('graphNodeNameV47').value='';document.getElementById('graphNodeStageV47').value='up';document.getElementById('graphNodeTypeV47').value='核心节点';var modal=document.getElementById('graphNodeEditModalV47');modal.classList.add('open');modal.setAttribute('aria-hidden','false');setTimeout(function(){document.getElementById('graphNodeNameV47').focus()},30)};
  window.openGraphNodeEditorV47=function(index){ensureGraphBuilderToolsV63();graphEditIndexV63=index;var node=graphBuilderNodes[index];if(!node)return;document.getElementById('graphNodeEditTitleV47').textContent='编辑产业链节点';document.getElementById('graphNodeNameV47').value=node.name;document.getElementById('graphNodeStageV47').value=node.stage;document.getElementById('graphNodeTypeV47').value=node.type;var modal=document.getElementById('graphNodeEditModalV47');modal.classList.add('open');modal.setAttribute('aria-hidden','false')};
  window.copyGraphNodeV63=function(index){var node=graphBuilderNodes[index];if(!node)return;var copy=JSON.parse(JSON.stringify(node));copy.name=node.name+'（副本）';copy.source='复制节点';graphBuilderNodes.splice(index+1,0,copy);renderGraphNodes();document.getElementById('graphPreviewStatus').textContent='节点已复制';if(typeof toast==='function')toast('节点已复制，可继续编辑')};
  window.saveGraphNodeEditorV47=function(){var name=document.getElementById('graphNodeNameV47').value.trim();if(!name){toast('请输入节点名称');return}var isNew=graphEditIndexV63===null,payload={name:name,stage:document.getElementById('graphNodeStageV47').value,type:document.getElementById('graphNodeTypeV47').value,source:isNew?'手工新增':'业务修正'};if(isNew)graphBuilderNodes.push(payload);else graphBuilderNodes[graphEditIndexV63]=Object.assign(graphBuilderNodes[graphEditIndexV63],payload);closeGraphNodeEditorV47();renderGraphNodes();document.getElementById('graphPreviewStatus').textContent=isNew?'已新增节点':'节点已编辑';graphEditIndexV63=null};
  window.renderGraphNodes=function(){ensureGraphBuilderToolsV63();['up','mid','down'].forEach(function(stage){var mount=document.getElementById('graphNodes'+stage.charAt(0).toUpperCase()+stage.slice(1));if(!mount)return;mount.classList.add('graph-stage-nodes-v47');mount.ondragover=window.dragOverGraphStageV47;mount.ondragleave=function(){this.classList.remove('drag-over')};mount.ondrop=function(event){dropGraphNodeV47(event,stage)};mount.innerHTML=graphBuilderNodes.map(function(node,index){return{node:node,index:index}}).filter(function(item){return item.node.stage===stage}).map(function(item){var service=item.node.type==='配套服务'?' service-node-v63':'';return'<article class="graph-preview-node graph-preview-node-v47'+service+'" draggable="true" data-node-index="'+item.index+'" ondragstart="startGraphNodeDragV47(event,'+item.index+')" ondragend="endGraphNodeDragV47(event)"><b>'+escV63(item.node.name)+'</b><span>'+escV63(item.node.type)+' · '+escV63(item.node.source)+'</span><div class="graph-node-actions-v47 graph-node-actions-v63"><button type="button" draggable="false" onclick="event.stopPropagation();openGraphNodeEditorV47('+item.index+')">编辑</button><button type="button" draggable="false" onclick="event.stopPropagation();copyGraphNodeV63('+item.index+')">复制</button><button type="button" draggable="false" onclick="event.stopPropagation();removeGraphNode('+item.index+')">×</button></div></article>'}).join('')||'<article class="graph-preview-node"><b>待补充节点</b><span>点击“新增节点”或由 AI 解析生成</span></article>'});document.getElementById('graphNodeCount').textContent='共 '+graphBuilderNodes.length+' 个节点 · 支持新增、复制、拖动、编辑和删除'};
  ensureGraphBuilderToolsV63();var previousOpenGraphV63=window.openGraphBuilder;if(previousOpenGraphV63)window.openGraphBuilder=function(){var result=previousOpenGraphV63.apply(this,arguments);ensureGraphBuilderToolsV63();renderGraphNodes();return result};
})();
