/* service-alignment-batch-recommend-and-chain-relations-v64 */
(function(){
  function escV64(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})}

  function nodeHtmlV64(node){return'<button class="chain-node '+escV64(node[2]||'')+'" data-chain="'+escV64(node[0])+'"><b>'+escV64(node[0])+'</b><span>'+escV64(node[1])+'</span>'+(node[3]?'<em class="'+(String(node[2]||'').indexOf('weak')>-1?'':'normal')+'">'+escV64(node[3])+'</em>':'')+'</button>'}
  window.renderIndustryGraph=function(key){
    var data=chainIndustryData[key];if(!data)return;activeChainKey=key;
    document.getElementById('chainIndustryTitle').textContent=data.name;document.getElementById('chainIndustryPath').textContent=data.path;document.getElementById('chainCompanyCount').textContent=data.companies+' 家';document.getElementById('chainCompleteness').textContent=data.complete+'%';document.getElementById('chainLocalRate').textContent=data.local+'%';document.getElementById('chainWeakCount').textContent=data.weak+' 个';
    var service=data.columns.find(function(column){return column.label.indexOf('配套服务')>-1}),main=data.columns.filter(function(column){return column!==service}).slice(0,3),serviceGroups=[[],[],[]];
    (service&&service.nodes||[]).forEach(function(node,index){serviceGroups[index%3].push(node)});
    var mainHtml=main.map(function(column,index){return(index?'<div class="chain-arrow">›</div>':'')+'<div class="chain-column"><label>'+escV64(column.label)+'</label>'+column.nodes.map(nodeHtmlV64).join('')+'</div>'}).join('');
    var labels=['上游专项服务','中游专项服务','下游专项服务'];
    var serviceHtml=service?'<section class="chain-service-band-v64"><header><div><b>配套服务节点</b><span>专项服务按主要服务对象对应上游、中游、下游布局，单个服务节点也可跨环节支撑</span></div></header><div class="chain-service-grid-v64">'+serviceGroups.map(function(nodes,index){return'<div class="service-stage-v64"><label>'+labels[index]+'</label><span class="service-guide-v64">'+(index===0?'支撑原料、研发与供应保障':index===1?'支撑制造、检测与生产协同':'支撑应用、市场与运营服务')+'</span>'+nodes.map(nodeHtmlV64).join('')+'</div>'}).join('')+'</div></section>':'';
    var flow=document.getElementById('chainFlow');flow.innerHTML='<div class="chain-main-v63">'+mainHtml+'</div>'+serviceHtml;
    flow.querySelectorAll('.chain-node').forEach(function(button){button.onclick=function(){flow.querySelectorAll('.chain-node').forEach(function(item){item.classList.remove('selected')});button.classList.add('selected');openNodeCompanyList(button.dataset.chain)}});var selected=flow.querySelector('.chain-node');if(selected)selected.classList.add('selected');
  };
  if(typeof activeChainKey!=='undefined')renderIndustryGraph(activeChainKey);

  var recommendSelectedV64=new Set();
  window.toggleRecommendV64=function(name,checked){checked?recommendSelectedV64.add(name):recommendSelectedV64.delete(name);updateRecommendBatchV64()};
  window.toggleAllRecommendV64=function(checked){document.querySelectorAll('#nodeCompanyRows .recommend-check-v64').forEach(function(input){input.checked=checked;toggleRecommendV64(decodeURIComponent(input.dataset.name),checked)});updateRecommendBatchV64()};
  function updateRecommendBatchV64(){var button=document.getElementById('nodeMoreFilterBtn');if(!button||!document.querySelector('#nodeCompanyTableHead .recommend-select-all-v64'))return;button.disabled=!recommendSelectedV64.size;button.className='primary node-batch-add-v64';button.textContent='一键批量加入名单（'+recommendSelectedV64.size+'）';button.onclick=batchAddRecommendV64}
  window.batchAddRecommendV64=function(){if(!recommendSelectedV64.size)return;recommendSelectedV64.forEach(function(name){if(typeof addInvestmentTarget==='function')addInvestmentTarget(name)});document.querySelectorAll('#nodeCompanyRows .recommend-check-v64').forEach(function(input){if(recommendSelectedV64.has(decodeURIComponent(input.dataset.name)))input.disabled=true});var count=recommendSelectedV64.size,button=document.getElementById('nodeMoreFilterBtn');button.disabled=true;button.textContent='✓ 已批量加入 '+count+' 家企业';toast('已将 '+count+' 家推荐企业批量加入招商名单')};
  window.returnLocalFromRecommendV64=function(){var modal=document.getElementById('nodeCompanyModal');modal.classList.remove('open');setTimeout(function(){openNodeCompanyList(currentNodeCompanyName)},20)};
  function enhanceRecommendV64(){
    var title=document.getElementById('nodeCompanyTitle'),head=document.getElementById('nodeCompanyTableHead'),body=document.getElementById('nodeCompanyRows');if(!title||!head||!body||title.textContent.indexOf('补强推荐企业')<0||head.querySelector('.recommend-select-all-v64'))return;
    recommendSelectedV64.clear();var companies=nodeExternalCompanies.slice().sort(function(a,b){return b.score-a.score}).slice(0,10),oldRows=Array.from(body.querySelectorAll('tr'));
    head.innerHTML='<tr><th class="recommend-select-v64"><input class="recommend-select-all-v64" type="checkbox" onchange="toggleAllRecommendV64(this.checked)"></th><th>推荐企业</th><th>所在地区</th><th>企业荣誉资质</th><th>主要补强能力</th><th>匹配度</th><th>联系方式</th></tr>';
    body.innerHTML=oldRows.map(function(row,index){var cells=row.children,company=companies[index]||{},name=cells[0]?.querySelector('b')?.textContent.trim()||company.name||'推荐企业',encoded=encodeURIComponent(name),honors=(company.tags||['待核验']).slice(0,3);return'<tr><td class="recommend-select-v64"><input class="recommend-check-v64" type="checkbox" data-name="'+encoded+'" onchange="toggleRecommendV64(decodeURIComponent(this.dataset.name),this.checked)"></td><td>'+cells[0].innerHTML+'</td><td>'+cells[1].innerHTML+'</td><td><div class="honor-tags-v64">'+honors.map(function(tag){return'<span>'+escV64(tag)+'</span>'}).join('')+'</div></td><td>'+cells[2].innerHTML+'</td><td>'+cells[3].innerHTML+'</td><td>'+cells[4].innerHTML+'</td></tr>'}).join('');
    var footer=document.getElementById('nodeMoreFilterBtn')?.parentElement;if(footer&&!document.getElementById('nodeReturnLocalV64')){var back=document.createElement('button');back.id='nodeReturnLocalV64';back.className='secondary';back.textContent='返回本地挂靠企业';back.onclick=returnLocalFromRecommendV64;footer.insertBefore(back,document.getElementById('nodeMoreFilterBtn'))}updateRecommendBatchV64();
  }
  var recommendBodyV64=document.getElementById('nodeCompanyRows');if(recommendBodyV64)new MutationObserver(function(){setTimeout(enhanceRecommendV64,0)}).observe(recommendBodyV64,{childList:true});

  var chainBatchModeV64=false,chainBatchSelectedV64=new Set(),batchOriginalRowsV64=null,previousBatchOpenV64=window.openChainEnterpriseRangeV47,previousBatchCloseV64=window.closeChainEnterpriseRangeV47;
  function batchButtonV64(){return document.getElementById('batchChainEnterpriseBtnV47')}
  function updateChainBatchButtonV64(){var button=batchButtonV64();if(!button)return;if(!chainBatchModeV64){button.disabled=false;button.textContent='批量企业上链';button.classList.remove('batch-active-v64');return}button.disabled=!chainBatchSelectedV64.size;button.textContent='批量企业上链（'+chainBatchSelectedV64.size+'）';button.classList.add('batch-active-v64')}
  window.toggleChainBatchRowV64=function(index,checked){checked?chainBatchSelectedV64.add(index):chainBatchSelectedV64.delete(index);updateChainBatchButtonV64()};
  window.toggleAllChainRowsV64=function(checked){document.querySelectorAll('#kbTableBody .chain-row-check-v64').forEach(function(input){input.checked=checked;toggleChainBatchRowV64(Number(input.dataset.index),checked)})};
  function decorateChainBatchV64(){if(activeKnowledgeType!=='chain'||!chainBatchModeV64)return;var head=document.querySelector('#kbTableHead tr');if(head&&!head.querySelector('.chain-batch-head-v64')){var th=document.createElement('th');th.className='chain-batch-head-v64';th.innerHTML='<input type="checkbox" onchange="toggleAllChainRowsV64(this.checked)">';head.insertBefore(th,head.firstChild)}Array.from(document.querySelectorAll('#kbTableBody>tr')).forEach(function(row,position){var item=activeKnowledgeRows[position];if(!item||row.querySelector('.chain-batch-cell-v64'))return;var td=document.createElement('td');td.className='chain-batch-cell-v64';td.innerHTML='<input class="chain-row-check-v64" type="checkbox" data-index="'+item.index+'" '+(chainBatchSelectedV64.has(item.index)?'checked':'')+' onchange="event.stopPropagation();toggleChainBatchRowV64('+item.index+',this.checked)" onclick="event.stopPropagation()">';row.insertBefore(td,row.firstChild)});updateChainBatchButtonV64()}
  window.startChainBatchV64=function(){if(!chainBatchModeV64){chainBatchModeV64=true;chainBatchSelectedV64.clear();renderKnowledgeList();updateChainBatchButtonV64();return}if(!chainBatchSelectedV64.size)return;batchOriginalRowsV64=activeKnowledgeRows.slice();activeKnowledgeRows=batchOriginalRowsV64.filter(function(item){return chainBatchSelectedV64.has(item.index)});previousBatchOpenV64(null,true)};
  var previousKnowledgeRenderV64=window.renderKnowledgeList;if(previousKnowledgeRenderV64)window.renderKnowledgeList=function(){var result=previousKnowledgeRenderV64.apply(this,arguments);decorateChainBatchV64();return result};
  var previousKnowledgeOpenV64=window.openKnowledgeBase;if(previousKnowledgeOpenV64)window.openKnowledgeBase=function(type){chainBatchModeV64=false;chainBatchSelectedV64.clear();var result=previousKnowledgeOpenV64.apply(this,arguments),button=batchButtonV64();if(button)button.onclick=startChainBatchV64;updateChainBatchButtonV64();return result};
  if(previousBatchCloseV64)window.closeChainEnterpriseRangeV47=function(){var result=previousBatchCloseV64.apply(this,arguments);if(batchOriginalRowsV64){activeKnowledgeRows=batchOriginalRowsV64;batchOriginalRowsV64=null;chainBatchModeV64=false;chainBatchSelectedV64.clear();renderKnowledgeList()}updateChainBatchButtonV64();return result};
  if(batchButtonV64())batchButtonV64().onclick=startChainBatchV64;

  var chainEditIndexV64=null;
  function chainNodesV64(row){var nodes=(row.graphNodes||[]).map(function(node){return node.name});if(!nodes.length)nodes=String(row.sub||'核心节点').split(/[—→]/).map(function(name){return name.trim()}).filter(Boolean);return nodes.length?nodes:['核心节点']}
  function ensureLinkedCompaniesV64(row){if(row.linkedCompanies)return row.linkedCompanies;var names=['海州智造科技有限公司','东岳动力科技有限公司','华驰汽车电子有限公司','新源固态电池有限公司','恒泰汽车零部件有限公司','海州精密传感科技有限公司','远航产业服务有限公司','海州创新技术有限公司'],nodes=chainNodesV64(row),relations=['主营产品关联','供应关系','技术协同','应用场景'];row.linkedCompanies=names.map(function(name,index){return{name:name,code:'9132'+String(10000000000000+index).slice(-14),node:nodes[index%nodes.length],type:index===0?'链主企业':'重点企业',relation:relations[index%relations.length],strength:(94-index*2)+'%',isLead:index===0}});return row.linkedCompanies}
  function refreshChainBasicEnterpriseV64(){var row=knowledgeBaseConfigs.chain.rows[chainEditIndexV64];if(!row)return;var companies=ensureLinkedCompaniesV64(row),mount=document.getElementById('chainEnterprisePreviewV64');if(!mount)return;mount.innerHTML=companies.slice(0,4).map(function(company){return'<button type="button" onclick="openChainCompanyManagerV49('+chainEditIndexV64+')"><span><b>'+escV64(company.name)+'</b><small>'+escV64(company.node)+' · '+escV64(company.relation||'主营产品关联')+'</small></span>'+(company.isLead?'<em>链主企业</em>':'<i>'+escV64(company.strength)+'</i>')+'</button>'}).join('');document.getElementById('chainEnterpriseLoadedV64').textContent=companies.length+' 条已加载';document.getElementById('chainEnterpriseLeadV64').textContent=companies.filter(function(company){return company.isLead}).length+' 家链主'}
  function patchChainBasicV64(){var modal=document.getElementById('chainBasicModalV61');if(!modal)return;var skeleton=modal.querySelector('.chain-skeleton-v61');if(skeleton)skeleton.hidden=true;var subtitle=modal.querySelector('header p');if(subtitle)subtitle.textContent='维护产业链基本信息与挂靠企业关系，节点结构请进入图谱画布编辑';var form=modal.querySelector('.chain-basic-form-v61');if(form&&!document.getElementById('chainEnterpriseEditorV64')){form.insertAdjacentHTML('afterend','<section class="chain-enterprise-editor-v64" id="chainEnterpriseEditorV64"><header><div><h3>挂靠企业关系</h3><p>支持人工新增企业挂靠、调整节点关系、修改关联强度并标注链主企业</p></div><button type="button" class="primary" onclick="openChainCompanyManagerV49('+chainEditIndexV64+')">管理挂靠企业 →</button></header><div class="chain-enterprise-stats-v64"><span><b id="chainEnterpriseLoadedV64">0 条已加载</b>企业关系明细</span><span><b id="chainEnterpriseLeadV64">0 家链主</b>链主企业标注</span><span><b>人工可校正</b>节点及关系类型</span></div><div class="chain-enterprise-preview-v64" id="chainEnterprisePreviewV64"></div></section>')}else if(document.getElementById('chainEnterpriseEditorV64'))document.querySelector('#chainEnterpriseEditorV64 header button').setAttribute('onclick','openChainCompanyManagerV49('+chainEditIndexV64+')');refreshChainBasicEnterpriseV64()}
  var previousBasicOpenV64=window.openChainBasicV61;if(previousBasicOpenV64)window.openChainBasicV61=function(index){chainEditIndexV64=index;var result=previousBasicOpenV64.apply(this,arguments);patchChainBasicV64();return result};

  var managerIndexV64=null;
  function updateLeadSummaryV64(row){var leads=ensureLinkedCompaniesV64(row).filter(function(company){return company.isLead}).map(function(company){return company.name});row.lead=leads.join('、')||'暂未标注链主企业'}
  window.updateChainRelationV64=function(index,field,value){var row=knowledgeBaseConfigs.chain.rows[managerIndexV64],company=ensureLinkedCompaniesV64(row)[index];if(!company)return;if(field==='isLead'){company.isLead=!!value;company.type=value?'链主企业':'重点企业';updateLeadSummaryV64(row)}else company[field]=field==='strength'?String(value).replace('%','')+'%':value;row.updatedAt=new Date().toLocaleString('zh-CN',{hour12:false}).replaceAll('/','-');renderChainCompaniesV64();refreshChainBasicEnterpriseV64()};
  window.renderChainCompaniesV64=function(){var row=knowledgeBaseConfigs.chain.rows[managerIndexV64];if(!row)return;var companies=ensureLinkedCompaniesV64(row),nodes=chainNodesV64(row),relations=['主营产品关联','供应关系','技术协同','应用场景','人工挂靠'];document.getElementById('chainCompanyTotalV49').textContent=row.companies||companies.length+' 家';document.getElementById('chainCompanyLoadedV49').textContent=companies.length+' 条';document.getElementById('chainCompanyPageTextV49').textContent='当前加载 '+companies.length+' 条关系明细';document.querySelector('#chainCompanyManagerV49 thead').innerHTML='<tr><th>企业名称</th><th>挂靠节点</th><th>关系类型</th><th>关联强度</th><th>链主企业</th><th>操作</th></tr>';document.getElementById('chainCompanyRowsV49').innerHTML=companies.map(function(company,index){return'<tr><td><b>'+escV64(company.name)+'</b><span>'+escV64(company.code||'待补充统一社会信用代码')+'</span></td><td><select onchange="updateChainRelationV64('+index+',\'node\',this.value)">'+nodes.map(function(node){return'<option '+(node===company.node?'selected':'')+'>'+escV64(node)+'</option>'}).join('')+'</select></td><td><select onchange="updateChainRelationV64('+index+',\'relation\',this.value)">'+relations.map(function(relation){return'<option '+(relation===(company.relation||'主营产品关联')?'selected':'')+'>'+relation+'</option>'}).join('')+'</select></td><td><input class="chain-strength-input-v64" type="number" min="0" max="100" value="'+parseInt(company.strength||80,10)+'" onchange="updateChainRelationV64('+index+',\'strength\',this.value)"><span class="strength-unit-v64">%</span></td><td><label class="lead-switch-v64"><input type="checkbox" '+(company.isLead?'checked':'')+' onchange="updateChainRelationV64('+index+',\'isLead\',this.checked)"><span></span><em>'+(company.isLead?'链主':'普通')+'</em></label></td><td><button type="button" onclick="unlinkChainCompanyV49('+index+')">解除挂靠</button></td></tr>'}).join('')||'<tr><td colspan="6">暂无挂靠企业</td></tr>';var average=companies.length?Math.round(companies.reduce(function(sum,company){return sum+(parseInt(company.strength,10)||0)},0)/companies.length):0;document.getElementById('chainCompanyStrengthV49').textContent=average+'%'};
  window.openChainCompanyManagerV49=function(index){managerIndexV64=index;var row=knowledgeBaseConfigs.chain.rows[index],nodes=chainNodesV64(row);ensureLinkedCompaniesV64(row);document.getElementById('chainCompanyManagerTitleV49').textContent=row.title+' · 挂靠企业关系';document.querySelector('#chainCompanyManagerV49 header p').textContent='人工维护企业与产业链节点的挂靠关系，支持链主标注、新增、修改和解绑';document.getElementById('chainCompanyAddNodeV49').innerHTML=nodes.map(function(node){return'<option>'+escV64(node)+'</option>'}).join('');document.getElementById('chainCompanyAddNameV49').value='';renderChainCompaniesV64();var modal=document.getElementById('chainCompanyManagerV49');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
  window.addChainCompanyV49=function(){var row=knowledgeBaseConfigs.chain.rows[managerIndexV64],input=document.getElementById('chainCompanyAddNameV49'),name=input.value.trim();if(!name){toast('请输入需要挂靠的企业名称');input.focus();return}var companies=ensureLinkedCompaniesV64(row);if(companies.some(function(company){return company.name===name})){toast('该企业已挂靠当前产业链');return}companies.unshift({name:name,code:'待补充统一社会信用代码',node:document.getElementById('chainCompanyAddNodeV49').value,type:'人工添加',relation:'人工挂靠',strength:'80%',isLead:false});row.companies=((parseInt(row.companies,10)||companies.length-1)+1)+' 家';input.value='';renderChainCompaniesV64();refreshChainBasicEnterpriseV64();renderKnowledgeList();toast('企业已新增挂靠，可继续调整关系')};
  window.unlinkChainCompanyV49=function(index){var row=knowledgeBaseConfigs.chain.rows[managerIndexV64],companies=ensureLinkedCompaniesV64(row),company=companies[index];if(!company)return;companies.splice(index,1);row.companies=Math.max(0,(parseInt(row.companies,10)||companies.length+1)-1)+' 家';updateLeadSummaryV64(row);renderChainCompaniesV64();refreshChainBasicEnterpriseV64();renderKnowledgeList();toast('已解除 '+company.name+' 的挂靠关系')};
  var previousManagerCloseV64=window.closeChainCompanyManagerV49;window.closeChainCompanyManagerV49=function(){var result=previousManagerCloseV64.apply(this,arguments);refreshChainBasicEnterpriseV64();if(document.getElementById('chainBasicModalV61')?.classList.contains('open'))document.body.style.overflow='hidden';return result};
})();
