(function(){
  'use strict';
  var profileSnapshotV84=null,profileTaskIndexV84=null;
  function notify(text){if(typeof window.toast==='function')window.toast(text)}
  function esc(value){return String(value==null?'':value).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
  function openModal(id){var modal=document.getElementById(id);if(!modal)return;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
  function closeModal(id){var modal=document.getElementById(id);if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
  function companyName(){var input=document.getElementById('epSearch'),card=document.querySelector('#enterprisePolicy .ep-company h2');return input&&input.value.trim()||card&&card.textContent.trim()||'海州智造科技有限公司'}
  function companyRow(name){return knowledgeBaseConfigs.company.rows.find(function(row){return !row.profileReviewTaskV84&&row.title===name})||knowledgeBaseConfigs.company.rows.find(function(row){return !row.profileReviewTaskV84})}
  function currentProfile(row){return {industry:row&&row.industryDetail||'制造业 / 汽车零部件及配件制造',products:row&&row.products||'智能座舱域控制器、车规级传感器',revenue:row&&row.revenue||'4亿～10亿',growth:row&&row.revenueGrowth||'18.6',rdExpense:row&&row.rdExpense||'4472',totalProfit:row&&row.totalProfit||'7346',netProfit:row&&row.netProfit||'6289',taxTotal:row&&row.taxTotal||'3158',employeeCount:row&&row.employeeCount||'386',rdEmployeeCount:row&&row.rdEmployeeCount||'62',totalAssets:row&&row.totalAssets||'86520',liabilityRatio:row&&row.liabilityRatio||'42.8',fixedAssets:row&&row.fixedAssets||'32760',equipmentValue:row&&row.equipmentValue||'28640',otherInfo:row&&row.otherPolicyInfo||'已完成数字化改造项目备案，近三年无重大失信。'} }
  var fieldDefs=[['industry','所属行业','profileIndustry'],['products','主营产品','profileProductInputV84'],['revenue','上年度营业收入区间','profileRevenue'],['growth','上年度营收增长率','profileRevenueGrowth'],['rdExpense','上年度研发费用总额','profileRdExpense'],['totalProfit','上年度利润总额','profileTotalProfit'],['netProfit','上年度净利润','profileNetProfit'],['taxTotal','上年度纳税总额','profileTaxTotal'],['employeeCount','当前职工数量','profileEmployeeCount'],['rdEmployeeCount','当前研发人员数量','profileRdEmployeeCount'],['totalAssets','上年度资产总额','profileTotalAssets'],['liabilityRatio','上年度资产负债率','profileAssetLiabilityRatio'],['fixedAssets','上年度固定资产总额','profileFixedAssets'],['equipmentValue','上年度累计设备原值','profileEquipmentOriginalValue'],['otherInfo','其他政策申报相关信息','profileOtherPolicyInfoV84']];
  function mountProfileFlow(){
    var modal=document.getElementById('profileModal'),body=modal&&modal.querySelector('.profile-modal-body');if(!body||document.getElementById('profileGovernanceV84'))return;
    body.insertAdjacentHTML('afterbegin','<div class="profile-governance-v84" id="profileGovernanceV84"><i>企</i><div><b id="profileGovernanceCompanyV84">当前企业</b><span id="profileGovernanceCodeV84">已读取企业库现有画像</span></div><em>企业库数据快照</em></div>');
    var productInput=body.querySelector('.chip-input input');if(productInput)productInput.id='profileProductInputV84';
    body.insertAdjacentHTML('beforeend','<section class="profile-extra-v84"><label><span>其他政策申报相关信息</span><textarea id="profileOtherPolicyInfoV84" placeholder="补充项目备案、融资、主导产品市场占有率、申报资质等信息"></textarea></label><label class="profile-proof-v84"><span>数据证明材料</span><input id="profileEvidenceV84" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png"><small>支持财务报表、纳税证明、研发台账、项目备案及其他申报证明材料</small></label></section>');
    document.body.insertAdjacentHTML('beforeend','<div class="prototype-modal-backdrop" id="profileUpdateDecisionV84" aria-hidden="true"><section class="prototype-modal profile-update-decision-v84"><header><div><label>ENTERPRISE PROFILE UPDATE</label><h2>本次补充信息如何使用？</h2><p>系统已使用补充信息重新计算政策匹配结果，请选择是否申请更新企业库正式画像。</p></div><button type="button" onclick="closeProfileDecisionV84()">×</button></header><div class="prototype-modal-body"><div class="profile-decision-company-v84"><i>企</i><div><b id="profileDecisionCompanyV84"></b><span id="profileDecisionCodeV84"></span></div><em id="profileDecisionChangeCountV84"></em></div><div class="profile-decision-options-v84"><article><b>仅本次匹配使用</b><p>补充数据只保存在本次政策匹配快照，不更新正式企业库，也不影响其他用户看到的企业画像。</p></article><article class="recommended"><b>本次使用并更新企业库画像</b><p>生成企业画像更新审核任务，由知识库运营审核员按字段核验，通过后更新正式画像并保留完整变更记录。</p></article></div><div class="profile-decision-note-v84">历史政策匹配报告不会被直接修改；正式入库后仅影响后续检索、画像与新建匹配任务。</div></div><footer><button class="secondary" type="button" onclick="useProfileSnapshotV84(false)">仅本次匹配使用</button><button class="primary" type="button" onclick="useProfileSnapshotV84(true)">本次使用并更新企业库画像</button></footer></section></div>');
  }
  function fillProfileForm(){
    var name=companyName(),row=companyRow(name),profile=currentProfile(row);document.getElementById('profileGovernanceCompanyV84').textContent=name;document.getElementById('profileGovernanceCodeV84').textContent='统一社会信用代码：'+(row&&row.code||'待企业主体校验')+' · 已读取企业库现有字段值';
    fieldDefs.forEach(function(def){var el=document.getElementById(def[2]);if(!el)return;var value=profile[def[0]]||'';if(def[0]==='products'){var chips=document.querySelector('#profileModal .chip-input');if(chips){Array.from(chips.querySelectorAll('em')).forEach(function(item){item.remove()});chips.insertAdjacentHTML('afterbegin',value.split('、').map(function(item){return '<em>'+esc(item)+' ×</em>'}).join(''))}el.value=''}else el.value=value});
  }
  function collectProfile(){
    var name=companyName(),row=companyRow(name),current=currentProfile(row),proof=document.getElementById('profileEvidenceV84'),proofNames=proof&&proof.files?Array.from(proof.files).map(function(file){return file.name}):[];
    var submitted={};fieldDefs.forEach(function(def){var el=document.getElementById(def[2]),value=el?el.value.trim():'';if(def[0]==='products'){var chips=Array.from(document.querySelectorAll('#profileModal .chip-input em')).map(function(item){return item.textContent.replace(/×/g,'').trim()});if(value)chips.push(value);value=chips.join('、')}submitted[def[0]]=value});
    var fields=fieldDefs.map(function(def){var oldValue=current[def[0]]||'未采集',newValue=submitted[def[0]]||'未填写',numeric=['growth','rdExpense','totalProfit','netProfit','taxTotal','employeeCount','rdEmployeeCount','totalAssets','liabilityRatio','fixedAssets','equipmentValue'].indexOf(def[0])>-1,abnormal=numeric&&newValue&&isNaN(Number(newValue)),conflict=(def[0]==='revenue'||def[0]==='rdExpense')&&oldValue!==newValue?'现有值曾人工审核，禁止自动覆盖，需重点复核':'';return {key:def[0],label:def[1],oldValue:oldValue,newValue:newValue,proof:proofNames.join('、')||'用户填报承诺，证明材料待补充',status:'pending',conflict:abnormal?'字段格式异常':conflict}});
    return {name:name,code:row&&row.code||'待校验',row:row,current:current,submitted:submitted,fields:fields,proofs:proofNames};
  }
  function refreshMatchWithSnapshot(snapshot){
    document.getElementById('profileCompleteness').textContent='100%';var count=document.getElementById('matchedPolicyCount');if(count)count.textContent='42';document.querySelectorAll('#enterprisePolicy .project-score b').forEach(function(score,index){score.textContent=[98,93,88][index]+'%'});var page=document.getElementById('enterprisePolicy'),banner=document.getElementById('enterpriseProfileSnapshotV84');if(!banner){banner=document.createElement('section');banner.id='enterpriseProfileSnapshotV84';banner.className='enterprise-profile-snapshot-v84';var overview=page.querySelector('.ep-overview-grid');overview.insertAdjacentElement('beforebegin',banner)}banner.innerHTML='<div><i>✓</i><div><b>已使用补充信息重新匹配政策</b><span>本次快照包含 '+snapshot.fields.length+' 个企业画像字段，匹配项目由 38 项更新为 42 项。</span></div></div><em>等待选择画像更新方式</em>';page.classList.add('matched');
  }
  window.saveEnterpriseProfile=function(){
    var industry=document.getElementById('profileIndustry'),revenue=document.getElementById('profileRevenue');if(!industry||!industry.value){notify('请选择所属行业');if(industry)industry.focus();return}if(!revenue||!revenue.value){notify('请选择上年度营业收入');if(revenue)revenue.focus();return}
    profileSnapshotV84=collectProfile();closeEnterpriseProfile();refreshMatchWithSnapshot(profileSnapshotV84);setTimeout(function(){document.getElementById('profileDecisionCompanyV84').textContent=profileSnapshotV84.name;document.getElementById('profileDecisionCodeV84').textContent='统一社会信用代码：'+profileSnapshotV84.code;document.getElementById('profileDecisionChangeCountV84').textContent=profileSnapshotV84.fields.length+' 个字段';openModal('profileUpdateDecisionV84')},280);
  };
  window.closeProfileDecisionV84=function(){closeModal('profileUpdateDecisionV84')};
  window.useProfileSnapshotV84=function(apply){
    if(!profileSnapshotV84)return;closeProfileDecisionV84();var banner=document.getElementById('enterpriseProfileSnapshotV84');if(!apply){if(banner)banner.querySelector('em').textContent='仅本次使用 · 未更新企业库';window.enterprisePolicySnapshotV84=profileSnapshotV84;notify('补充信息仅用于本次政策匹配，正式企业画像未更新');return}
    var source=profileSnapshotV84.row||{},task={profileReviewTaskV84:true,reviewId:'ENT-PROFILE-'+Date.now(),title:profileSnapshotV84.name,sub:'企业画像更新审核任务 · '+profileSnapshotV84.fields.length+' 个字段待核验',code:profileSnapshotV84.code,category:source.category||'新能源汽车',level:source.level||'市级',region:source.region||'江苏省 / 海州市',capital:source.capital||'待核验',honor:source.honor||'待核验',date:'2026-08-24',reviewStatus:'pending',status:'待审核',submitter:'政策服务人员 · 李敏',department:'海州市工业和信息化局 · 企业服务处',submitTime:'2026-08-24 18:30',targetCode:profileSnapshotV84.code,fields:profileSnapshotV84.fields,proofs:profileSnapshotV84.proofs,subjectCheck:'企业名称与统一社会信用代码一致',formatCheck:'已完成字段格式与数值范围预校验',publicDataCheck:'待与政府公示、采购及数据厂商信息比对',timeliness:'本次填报数据口径：上年度 / 当前',conflictSummary:profileSnapshotV84.fields.filter(function(field){return field.conflict}).length+' 个字段存在冲突或重点复核提示',historyPolicy:'历史政策匹配报告保持原版本，不直接修改'};knowledgeBaseConfigs.company.rows.unshift(task);profileTaskIndexV84=0;if(banner)banner.querySelector('em').textContent='画像更新申请 · 待审核';notify('已生成企业画像更新审核任务，可前往企业库按字段审核');
  };
  var previousOpenProfile=window.openEnterpriseProfile;window.openEnterpriseProfile=function(){mountProfileFlow();fillProfileForm();return previousOpenProfile.apply(this,arguments)};
  function enhanceCompanyTaskTable(){
    if(typeof activeKnowledgeType==='undefined'||activeKnowledgeType!=='company')return;var head=document.querySelector('#kbTableHead tr'),body=document.getElementById('kbTableBody');if(!head||!body)return;if(!head.querySelector('.company-review-head-v84')){var submitter=document.createElement('th');submitter.className='company-review-head-v84';submitter.textContent='提交人';head.insertBefore(submitter,head.lastElementChild);var status=document.createElement('th');status.className='company-review-head-v84';status.textContent='画像审核状态';head.insertBefore(status,head.lastElementChild)}
    Array.from(body.querySelectorAll('tr')).forEach(function(tr,position){var item=activeKnowledgeRows[position];if(!item)return;var row=item.row,action=tr.lastElementChild,submitter=document.createElement('td'),status=document.createElement('td');submitter.innerHTML=row.profileReviewTaskV84?'<b>'+esc(row.submitter)+'</b><small>'+esc(row.submitTime)+'</small>':'<span>企业主数据</span>';status.innerHTML=row.profileReviewTaskV84?'<em class="company-review-badge-v84 '+row.reviewStatus+'">'+(row.reviewStatus==='pending'?'待字段审核':row.reviewStatus==='approved'?'已正式入库':row.reviewStatus==='partial'?'部分通过':'已驳回')+'</em>':'<em class="company-review-badge-v84 approved">正式画像</em>';tr.insertBefore(submitter,action);tr.insertBefore(status,action);if(row.profileReviewTaskV84){tr.classList.add('company-profile-task-row-v84');action.innerHTML='<button class="kb-row-action" onclick="event.stopPropagation();openKnowledgeDetail('+item.index+')">查看审核任务 →</button>'}}
    );
  }
  function renderCompanyReviewTask(row,index){
    profileTaskIndexV84=index;document.getElementById('kbDetailType').textContent='企业库 · 企业画像更新审核任务';document.getElementById('kbDetailTitle').textContent=row.title;document.getElementById('kbDetailMeta').textContent='任务 '+row.reviewId+' · '+row.submitter+' · '+row.submitTime;
    var rows=row.fields.map(function(field,i){return '<tr><td><b>'+esc(field.label)+'</b><small>'+esc(field.key)+'</small></td><td>'+esc(field.oldValue)+'</td><td>'+esc(field.newValue)+'</td><td>'+esc(field.proof)+'</td><td>'+(field.conflict?'<em class="field-conflict-v84">'+esc(field.conflict)+'</em>':'<span class="field-normal-v84">未发现异常</span>')+'</td><td><select data-profile-field-review="'+i+'"><option value="pending" '+(field.status==='pending'?'selected':'')+'>待审核</option><option value="approved" '+(field.status==='approved'?'selected':'')+'>通过</option><option value="rejected" '+(field.status==='rejected'?'selected':'')+'>驳回</option><option value="conflict" '+(field.status==='conflict'?'selected':'')+'>冲突待核验</option></select></td></tr>'}).join('');
    document.getElementById('kbDetailBody').innerHTML='<section class="company-task-overview-v84"><div><span>企业主体</span><b>'+esc(row.title)+'</b><em>'+esc(row.code)+'</em></div><div><span>提交人及部门</span><b>'+esc(row.submitter)+'</b><em>'+esc(row.department)+'</em></div><div><span>任务状态</span><b>待字段级审核</b><em>'+row.fields.length+' 个字段</em></div><div><span>冲突检测</span><b>'+esc(row.conflictSummary)+'</b><em>禁止自动覆盖已审核值</em></div></section><section class="company-review-checks-v84"><b>审核核验清单</b><span>① '+esc(row.subjectCheck)+'</span><span>② '+esc(row.formatCheck)+'</span><span>③ 与企业库现有数据比较</span><span>④ '+esc(row.publicDataCheck)+'</span><span>⑤ 证明材料核验</span><span>⑥ '+esc(row.timeliness)+'</span><span>⑦ 冲突数据人工处理</span></section><section class="kb-detail-section"><h3>字段变更前后对比与审核结论</h3><div class="company-field-review-wrap-v84"><table><thead><tr><th>字段</th><th>企业库当前值</th><th>用户提交值</th><th>证明材料</th><th>冲突/异常</th><th>字段审核结果</th></tr></thead><tbody>'+rows+'</tbody></table></div></section><div class="company-review-rule-v84"><b>数据冲突规则：</b>已由用户补充且审核通过的字段锁定为“人工核验值”，后续数据厂商季度更新不得直接覆盖，仅标记“有更新”并进入人工复核。正式入库会保存原值、新值、审核人、审核时间、来源和可信等级；'+esc(row.historyPolicy)+'。</div>';
    var modal=document.getElementById('kbDetailModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';mountCompanyReviewFooter(row);
  }
  function cleanDetailFooter(){var footer=document.querySelector('#kbDetailModal .kb-detail-dialog>footer'),extra=document.getElementById('detailWorkflowActionsV84'),save=footer&&footer.querySelector('button.primary');if(extra)extra.remove();if(save)save.style.display=''}
  function mountPolicyReviewFooter(index){
    cleanDetailFooter();if(typeof activeKnowledgeType==='undefined'||activeKnowledgeType!=='policy')return;var row=knowledgeBaseConfigs.policy.rows[index],footer=document.querySelector('#kbDetailModal .kb-detail-dialog>footer');if(!row||!footer||row.reviewStatus!=='pending'||!row.reviewId)return;var bodyActions=document.querySelector('#policyDetailGovernanceV83 .policy-detail-review-actions-v83');if(bodyActions)bodyActions.remove();var actions=document.createElement('div');actions.id='detailWorkflowActionsV84';actions.className='detail-workflow-actions-v84';actions.innerHTML='<button class="review-reject-v84" type="button" onclick="openPolicyAuditV78(\''+row.reviewId+'\',\'reject\')">驳回</button><button class="review-approve-v84" type="button" onclick="openPolicyAuditV78(\''+row.reviewId+'\',\'approve\')">审核通过</button>';var save=footer.querySelector('button.primary');footer.insertBefore(actions,save||null);
  }
  function mountCompanyReviewFooter(row){
    cleanDetailFooter();var footer=document.querySelector('#kbDetailModal .kb-detail-dialog>footer');if(!footer)return;var actions=document.createElement('div');actions.id='detailWorkflowActionsV84';actions.className='detail-workflow-actions-v84';actions.innerHTML='<button class="secondary" type="button" onclick="saveEnterpriseFieldReviewV84(false)">保存审核进度</button><button class="primary" type="button" onclick="saveEnterpriseFieldReviewV84(true)">完成审核并正式入库</button>';var save=footer.querySelector('button.primary');if(save)save.style.display='none';footer.appendChild(actions);
  }
  window.saveEnterpriseFieldReviewV84=function(complete){
    var task=knowledgeBaseConfigs.company.rows[profileTaskIndexV84];if(!task||!task.profileReviewTaskV84)return;document.querySelectorAll('[data-profile-field-review]').forEach(function(select){task.fields[Number(select.dataset.profileFieldReview)].status=select.value});if(!complete){task.lastSavedAt='2026-08-24 18:42';notify('字段审核进度已保存');return}
    var unresolved=task.fields.filter(function(field){return field.status==='pending'||field.status==='conflict'});if(unresolved.length){notify('仍有 '+unresolved.length+' 个字段待审核或冲突待核验，暂不能正式入库');return}var approved=task.fields.filter(function(field){return field.status==='approved'}),rejected=task.fields.filter(function(field){return field.status==='rejected'}),target=knowledgeBaseConfigs.company.rows.find(function(row){return !row.profileReviewTaskV84&&row.code===task.targetCode});if(target){target.profileData=target.profileData||{};target.fieldLocks=target.fieldLocks||{};target.profileAuditHistory=target.profileAuditHistory||[];approved.forEach(function(field){target.profileData[field.key]=field.newValue;target[field.key]=field.newValue;target.fieldLocks[field.key]=true;target.profileAuditHistory.push({field:field.label,oldValue:field.oldValue,newValue:field.newValue,auditor:'知识库运营审核员 · 王宁',auditTime:'2026-08-24 18:48',source:'企业用户补充 + 证明材料',confidence:'人工核验 / 高'})});target.searchIndexRefreshed=true;target.vendorUpdateMode='仅标记有更新，不自动覆盖'}task.reviewStatus=rejected.length?(approved.length?'partial':'rejected'):'approved';task.status=task.reviewStatus==='approved'?'已正式入库':task.reviewStatus==='partial'?'部分字段入库':'已驳回';task.auditor='知识库运营审核员 · 王宁';task.auditTime='2026-08-24 18:48';task.resultNotice='已通知提交人';renderKnowledgeList();openKnowledgeDetail(profileTaskIndexV84);notify('字段审核已完成：通过 '+approved.length+' 项，驳回 '+rejected.length+' 项；企业检索与画像索引已刷新');
  };
  var previousRender=window.renderKnowledgeList;window.renderKnowledgeList=function(){var result=previousRender.apply(this,arguments);enhanceCompanyTaskTable();return result};
  var previousDetail=window.openKnowledgeDetail;window.openKnowledgeDetail=function(index){cleanDetailFooter();if(typeof activeKnowledgeType!=='undefined'&&activeKnowledgeType==='company'){var row=knowledgeBaseConfigs.company.rows[index];if(row&&row.profileReviewTaskV84){renderCompanyReviewTask(row,index);return}}var result=previousDetail.apply(this,arguments);mountPolicyReviewFooter(index);return result};
  mountProfileFlow();
  if(typeof prototypeLogicAnnotations!=='undefined'){prototypeLogicAnnotations.enterprisePolicy.interactions.push(['企业画像补充与更新申请','选择企业并完善缺失字段，提交后先用补充数据重新匹配政策。','用户选择仅本次使用或提交企业画像更新审核；本次快照不直接覆盖企业库，历史匹配报告保持原版本。']);prototypeLogicAnnotations.knowledgeList.interactions.push(['企业画像字段级审核','企业库打开画像更新审核任务。','逐字段比对原值与提交值，核验证明材料、格式、时效性和冲突；仅通过字段正式入库并锁定为人工核验值，厂商新数据只提示“有更新”。'])}
})();
