(function(){
  'use strict';
  var profileSnapshotV84=null,profileTaskIndexV84=null,confirmedProfilesV84=Object.create(null);
  function notify(text){if(typeof window.toast==='function')window.toast(text)}
  function esc(value){return String(value==null?'':value).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
  function openModal(id){var modal=document.getElementById(id);if(!modal)return;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
  function closeModal(id){var modal=document.getElementById(id);if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
  function companyName(){var input=document.getElementById('epSearch'),card=document.querySelector('#enterprisePolicy .ep-company h2');return input&&input.value.trim()||card&&card.textContent.trim()||'海州智造科技有限公司'}
  function companyRow(name){return knowledgeBaseConfigs.company.rows.find(function(row){return !row.profileReviewTaskV84&&row.title===name})||knowledgeBaseConfigs.company.rows.find(function(row){return !row.profileReviewTaskV84})}
  // Numeric values use 万元; legacy ranges cannot supply an exact amount.
  function revenueInWanV84(value){
    var raw=String(value==null?'':value).replace(/[,，\s]/g,'');
    if(raw!==''&&isFinite(Number(raw))&&Number(raw)>=0)return String(Number(raw));
    var match=raw.match(/^(\d+(?:\.\d+)?)(亿元?|万元?|元)?$/);
    if(!match)return '';
    var amount=Number(match[1]),unit=match[2]||'万';
    if(unit.charAt(0)==='亿')amount*=10000;
    else if(unit==='元')amount/=10000;
    return isFinite(amount)?String(amount):'';
  }
  function profileValueV84(row,key,fallback){return row&&Object.prototype.hasOwnProperty.call(row,key)?(row[key]==null?'':String(row[key])):fallback}
  function baseProfileV84(row){return {industry:profileValueV84(row,'industryDetail','制造业 / 汽车零部件及配件制造'),products:profileValueV84(row,'products','智能座舱域控制器、车规级传感器'),revenue:revenueInWanV84(row&&(row.revenueWan!=null?row.revenueWan:row.revenue)),growth:profileValueV84(row,'revenueGrowth','18.6'),rdExpense:profileValueV84(row,'rdExpense','4472'),totalProfit:profileValueV84(row,'totalProfit','7346'),netProfit:profileValueV84(row,'netProfit','6289'),taxTotal:profileValueV84(row,'taxTotal','3158'),employeeCount:profileValueV84(row,'employeeCount','386'),rdEmployeeCount:profileValueV84(row,'rdEmployeeCount','62'),totalAssets:profileValueV84(row,'totalAssets','86520'),liabilityRatio:profileValueV84(row,'liabilityRatio','42.8'),fixedAssets:profileValueV84(row,'fixedAssets','32760'),equipmentValue:profileValueV84(row,'equipmentValue','28640'),inventionPatentGrantCount:profileValueV84(row,'inventionPatentGrantCount','9'),designPatentCount:profileValueV84(row,'designPatentCount','3'),utilityModelPatentCount:profileValueV84(row,'utilityModelPatentCount','11'),softwareCopyrightCount:profileValueV84(row,'softwareCopyrightCount','16'),trademarkCount:profileValueV84(row,'trademarkCount','8'),otherInfo:row&&(row.otherPolicyInfo!=null?row.otherPolicyInfo:row.otherInfo)||''} }
  function currentProfile(row){
    var profile=baseProfileV84(row);
    var aliases={establishedYears:["establishedYears","age"],honor:["honor","honors"],marketPosition:["marketPosition","marketShareRanking"],taxCreditGrade:["taxCreditGrade","taxCredit"],standardsParticipation:["standardsParticipation","standards"],seriousDishonesty:["seriousDishonesty"]};
    Object.keys(aliases).forEach(function(key){var value="";aliases[key].some(function(name){if(row&&row[name]!=null&&row[name]!==""){value=row[name];return true}return false});if(Array.isArray(value))value=value.join("、");if(key==="seriousDishonesty"&&typeof value==="boolean")value=value?"是":"否";profile[key]=String(value)});
    if(profile.establishedYears===""&&row&&/^\d{4}-\d{2}-\d{2}$/.test(row.date||"")){
      var parts=row.date.split("-").map(Number),created=Date.UTC(parts[0],parts[1]-1,parts[2]),date=new Date(created),now=new Date(),today=Date.UTC(now.getFullYear(),now.getMonth(),now.getDate());
      if(date.getUTCFullYear()===parts[0]&&date.getUTCMonth()===parts[1]-1&&date.getUTCDate()===parts[2]&&created<=today)profile.establishedYears=((today-created)/(365*86400000)).toFixed(1);
    }
    if(row&&row.profileData)Object.keys(row.profileData).forEach(function(key){profile[key]=row.profileData[key]==null?'':String(row.profileData[key])});
    profile.revenue=revenueInWanV84(profile.revenue);
    return profile;
  }
  var fieldDefs=[['industry','所属行业','profileIndustry'],['products','主营产品','profileProductInputV84'],['revenue','上年度营业收入（万元）','profileRevenue'],['growth','上年度营收增长率','profileRevenueGrowth'],['rdExpense','上年度研发费用总额','profileRdExpense'],['totalProfit','上年度利润总额','profileTotalProfit'],['netProfit','上年度净利润','profileNetProfit'],['taxTotal','上年度纳税总额','profileTaxTotal'],['employeeCount','社保人数','profileEmployeeCount'],['rdEmployeeCount','当前研发人员数量','profileRdEmployeeCount'],['totalAssets','上年度资产总额','profileTotalAssets'],['liabilityRatio','上年度资产负债率','profileAssetLiabilityRatio'],['fixedAssets','上年度固定资产总额','profileFixedAssets'],['equipmentValue','上年度累计设备原值','profileEquipmentOriginalValue'],['inventionPatentGrantCount','发明专利授权数','profileInventionPatentGrantCountV117'],['designPatentCount','外观设计数','profileDesignPatentCountV117'],['utilityModelPatentCount','实用新型数','profileUtilityModelPatentCountV117'],['softwareCopyrightCount','软件著作权数量','profileSoftwareCopyrightCountV117'],['trademarkCount','商标数','profileTrademarkCountV117'],["establishedYears","成立年限","profileEstablishedYearsV84"],["honor","荣誉资质","profileHonorV84"],["marketPosition","主导产品细分市场占有率/排名","profileMarketPositionV84"],["taxCreditGrade","纳税信用等级","profileTaxCreditGradeV84"],["standardsParticipation","标准参与情况","profileStandardsV84"],["seriousDishonesty","是否列入严重失信主体名单","profileSeriousDishonestyV84"],["otherInfo","其他补充信息","profileOtherInfoV84"]];
  function mountProfileFlow(){
    var modal=document.getElementById('profileModal'),body=modal&&modal.querySelector('.profile-modal-body');if(!body||document.getElementById('profileGovernanceV84'))return;
    body.insertAdjacentHTML('afterbegin','<div class="profile-governance-v84" id="profileGovernanceV84"><i>企</i><div><b id="profileGovernanceCompanyV84">当前企业</b><span id="profileGovernanceCodeV84">已读取企业库现有画像</span></div><em>企业库数据快照</em></div>');
    var productInput=body.querySelector('.chip-input input');if(productInput)productInput.id='profileProductInputV84';
    body.insertAdjacentHTML('beforeend',"<section class=\"profile-grid profile-section profile-qualification-v84\" aria-label=\"企业资质与政策条件\"><label><span>成立年限</span><div class=\"unit-input\"><input id=\"profileEstablishedYearsV84\" type=\"number\" min=\"0\" step=\"0.1\" inputmode=\"decimal\" placeholder=\"请输入成立年限\"><b>年</b></div></label><label><span>荣誉资质</span><input id=\"profileHonorV84\" maxlength=\"500\" placeholder=\"如高新技术企业、专精特新，可填写多项\"></label><label><span>主导产品细分市场占有率/排名</span><textarea id=\"profileMarketPositionV84\" maxlength=\"1000\" placeholder=\"填写产品、市场范围、占有率或排名及统计年度\"></textarea></label><label><span>纳税信用等级</span><select id=\"profileTaxCreditGradeV84\"><option value=\"\">请选择</option><option>A级</option><option>B级</option><option>M级</option><option>C级</option><option>D级</option><option>未评级</option></select></label><label><span>标准参与情况</span><textarea id=\"profileStandardsV84\" maxlength=\"1000\" placeholder=\"填写主导或参与制定的标准名称、级别及角色\"></textarea></label><label><span>是否列入严重失信主体名单</span><select id=\"profileSeriousDishonestyV84\"><option value=\"\">请选择</option><option>是</option><option>否</option><option>待核验</option></select></label></section>");
    body.insertAdjacentHTML('beforeend','<section class="profile-grid profile-section profile-ip-v117" aria-label="知识产权"><div class="profile-ip-head-v117"><div><i>知</i><span><b>知识产权</b><small>按有效状态填写，用于政策核心知识产权条件判定</small></span></div><em>5 项新增字段</em></div><label><span>发明专利授权数</span><div class="unit-input"><input id="profileInventionPatentGrantCountV117" type="number" min="0" step="1" inputmode="numeric" placeholder="请输入"><b>件</b></div></label><label><span>外观设计数</span><div class="unit-input"><input id="profileDesignPatentCountV117" type="number" min="0" step="1" inputmode="numeric" placeholder="请输入"><b>件</b></div></label><label><span>实用新型数</span><div class="unit-input"><input id="profileUtilityModelPatentCountV117" type="number" min="0" step="1" inputmode="numeric" placeholder="请输入"><b>件</b></div></label><label><span>软件著作权数量</span><div class="unit-input"><input id="profileSoftwareCopyrightCountV117" type="number" min="0" step="1" inputmode="numeric" placeholder="请输入"><b>项</b></div></label><label><span>商标数</span><div class="unit-input"><input id="profileTrademarkCountV117" type="number" min="0" step="1" inputmode="numeric" placeholder="请输入"><b>件</b></div></label></section>');
  }
  function profileKeyV84(name,row){return name+'|'+(row&&row.code||'')}
  function mountProfileSectionsV84(){
    var body=document.querySelector('#profileModal .profile-modal-body');
    if(!body||document.getElementById('profilePendingV84'))return;
    body.insertAdjacentHTML('beforeend','<section class="profile-info-section profile-info-pending" id="profilePendingV84" aria-labelledby="profilePendingTitleV84"><header class="profile-info-heading"><span class="profile-section-number">01</span><div><h3 id="profilePendingTitleV84">待补充信息 <span id="profilePendingCountV84" class="profile-section-count"></span></h3><p>请补充缺失字段，帮助完善政策匹配结果</p></div></header><div class="profile-grid profile-section-fields" id="profilePendingFieldsV84"></div><p class="profile-fields-complete" id="profileFieldsCompleteV84" hidden>固定字段已收集完整，可继续填写其他补充信息。</p><div class="profile-other-info"><label for="profileOtherInfoV84">其他补充信息 <span>选填</span></label><textarea id="profileOtherInfoV84" maxlength="2000" placeholder="可补充企业经营、项目建设、融资情况或其他与政策申报相关的信息"></textarea></div></section><details class="profile-info-section profile-info-collected" id="profileCollectedV84"><summary class="profile-info-heading" id="profileCollectedToggleV84"><span class="profile-section-number">02</span><div><h3>已收集信息 <span id="profileCollectedCountV84" class="profile-section-count"></span></h3><p>已有企业信息，可展开核对并修改</p></div><span class="profile-section-toggle"><span class="profile-expand-copy">展开修改</span><span class="profile-collapse-copy">收起</span><i aria-hidden="true">⌄</i></span></summary><div class="profile-grid profile-section-fields" id="profileCollectedFieldsV84"></div><p class="profile-fields-complete" id="profileCollectedEmptyV84" hidden>暂无已收集信息，请在上方补充。</p></details>');
  }
  function splitProfileFieldsV84(profile){
    mountProfileSectionsV84();
    var pending=document.getElementById('profilePendingFieldsV84'),collected=document.getElementById('profileCollectedFieldsV84'),missing=0,known=0;
    fieldDefs.forEach(function(def){
      if(def[0]==='otherInfo')return;
      var el=document.getElementById(def[2]),field=el&&el.closest('label,.enterprise-profile-honors-field');
      if(!field)return;
      var value=String(profile[def[0]]==null?'':profile[def[0]]).trim();
      var available=value!==''&&['未采集','未填写','待补充','待核验','暂无','未知','未提供'].indexOf(value)===-1;
      field.dataset.profileField=def[0];
      (available?collected:pending).appendChild(field);
      if(available)known++;else missing++;
    });
    document.querySelectorAll('#profileModal .profile-modal-body > .profile-section').forEach(function(section){section.remove()});
    document.getElementById('profilePendingCountV84').textContent=missing+' 项';
    document.getElementById('profileCollectedCountV84').textContent=known+' 项';
    document.getElementById('profileFieldsCompleteV84').hidden=missing>0;
    document.getElementById('profileCollectedEmptyV84').hidden=known>0;
    document.getElementById('profileCollectedV84').open=false;
  }
  function focusProfileFieldV84(input){
    var section=input&&input.closest('details');
    if(section)section.open=true;
    if(input)input.focus();
  }
  function fillProfileForm(){
    mountProfileSectionsV84();
    var name=companyName(),row=companyRow(name),saved=confirmedProfilesV84[profileKeyV84(name,row)],profile=Object.assign(currentProfile(row),saved||{});document.getElementById('profileGovernanceCompanyV84').textContent=name;document.getElementById('profileGovernanceCodeV84').textContent='统一社会信用代码：'+(row&&row.code||'待企业主体校验')+(saved?' · 已读取本次完善信息':' · 已读取企业库现有字段值');
    fieldDefs.forEach(function(def){var el=document.getElementById(def[2]);if(!el)return;var value=profile[def[0]]==null?'':profile[def[0]];if(def[0]==='products'){var chips=document.querySelector('#profileModal .chip-input');if(chips){Array.from(chips.querySelectorAll('em')).forEach(function(item){item.remove()});chips.insertAdjacentHTML('afterbegin',value.split('、').filter(function(item){return item.trim()!==''}).map(function(item){return '<em>'+esc(item)+' ×</em>'}).join(''))}el.value=''}else el.value=value});
    splitProfileFieldsV84(profile);
    document.querySelector('#profileModal .profile-modal-body').scrollTop=0;
  }
  function collectProfile(){
    var name=companyName(),row=companyRow(name),current=currentProfile(row),proof=document.getElementById('profileEvidenceV84'),proofNames=proof&&proof.files?Array.from(proof.files).map(function(file){return file.name}):[];
    var submitted={};fieldDefs.forEach(function(def){var el=document.getElementById(def[2]),value=el?el.value.trim():'';if(def[0]==='products'){var chips=Array.from(document.querySelectorAll('#profileModal .chip-input em')).map(function(item){return item.textContent.replace(/×/g,'').trim()});if(value)chips.push(value);value=chips.join('、')}if(def[0]==='revenue'&&value!=='')value=String(Number(value));submitted[def[0]]=value});
    var fields=fieldDefs.map(function(def){var oldValue=current[def[0]]||'未采集',newValue=submitted[def[0]]||'未填写',numeric=['revenue','growth','rdExpense','totalProfit','netProfit','taxTotal','employeeCount','rdEmployeeCount','totalAssets','liabilityRatio','fixedAssets','equipmentValue','inventionPatentGrantCount','designPatentCount','utilityModelPatentCount','softwareCopyrightCount','trademarkCount','establishedYears'].indexOf(def[0])>-1,abnormal=numeric&&submitted[def[0]]!==''&&!isFinite(Number(submitted[def[0]])),conflict=(def[0]==='revenue'||def[0]==='rdExpense')&&oldValue!==newValue?'现有值曾人工审核，禁止自动覆盖，需重点复核':'';return {key:def[0],label:def[1],oldValue:oldValue,newValue:newValue,proof:proofNames.join('、')||'用户填报承诺，证明材料待补充',status:'pending',conflict:abnormal?'字段格式异常':conflict}});
    return {name:name,code:row&&row.code||'待校验',row:row,current:current,submitted:submitted,fields:fields,proofs:proofNames};
  }
  function refreshMatchWithSnapshot(snapshot){
    document.getElementById('profileCompleteness').textContent='100%';var count=document.getElementById('matchedPolicyCount');if(count)count.textContent='42';document.querySelectorAll('#enterprisePolicy .project-score b').forEach(function(score,index){score.textContent=[98,93,88][index]+'%'});var page=document.getElementById('enterprisePolicy'),banner=document.getElementById('enterpriseProfileSnapshotV84');if(!banner){banner=document.createElement('section');banner.id='enterpriseProfileSnapshotV84';banner.className='enterprise-profile-snapshot-v84';var overview=page.querySelector('.ep-overview-grid');overview.insertAdjacentElement('beforebegin',banner)}banner.innerHTML='<div><i>✓</i><div><b>已使用补充信息重新匹配政策</b><span>本次快照包含 '+snapshot.fields.length+' 个企业画像字段，匹配项目由 38 项更新为 42 项。</span></div></div><em>匹配结果已更新</em>';page.classList.add('matched');
  }
  window.saveEnterpriseProfile=function(){
    var industry=document.getElementById('profileIndustry'),revenue=document.getElementById('profileRevenue');if(!industry||!industry.value){notify('请选择所属行业');if(industry)focusProfileFieldV84(industry);return false}if(!revenue||!revenue.value){notify('请输入上年度营业收入（万元）');if(revenue)focusProfileFieldV84(revenue);return false}
    if(!revenue.validity.valid||!isFinite(Number(revenue.value))||Number(revenue.value)<0){notify('上年度营业收入请输入大于或等于0的数字（万元）');focusProfileFieldV84(revenue);return false}
    var years=document.getElementById("profileEstablishedYearsV84");if(years&&(!years.validity.valid||(years.value!==""&&(!isFinite(Number(years.value))||Number(years.value)<0)))){notify("成立年限请输入大于或等于0的数字，最多保留1位小数");focusProfileFieldV84(years);return false}
    var countIds=['profileInventionPatentGrantCountV117','profileDesignPatentCountV117','profileUtilityModelPatentCountV117','profileSoftwareCopyrightCountV117','profileTrademarkCountV117'];for(var i=0;i<countIds.length;i++){var countInput=document.getElementById(countIds[i]);if(countInput&&countInput.value!==''&&(!countInput.validity.valid||!/^\d+$/.test(countInput.value))){notify(countInput.closest('label').querySelector('span').textContent+'请输入大于或等于0的整数');focusProfileFieldV84(countInput);return false}}
    profileSnapshotV84=collectProfile();confirmedProfilesV84[profileKeyV84(profileSnapshotV84.name,profileSnapshotV84.row)]=Object.assign({},profileSnapshotV84.submitted);window.enterprisePolicySnapshotV84=profileSnapshotV84;closeEnterpriseProfile();refreshMatchWithSnapshot(profileSnapshotV84);notify('企业信息已确认，匹配结果已更新');
    return true;
  };
  window.closeProfileDecisionV84=function(){closeModal('profileUpdateDecisionV84')};
  window.useProfileSnapshotV84=function(apply){
    if(!profileSnapshotV84)return;closeProfileDecisionV84();window.enterprisePolicySnapshotV84=profileSnapshotV84;var banner=document.getElementById('enterpriseProfileSnapshotV84');if(!apply){if(banner)banner.querySelector('em').textContent='仅本次使用 · 未更新企业库';window.enterprisePolicySnapshotV84=profileSnapshotV84;notify('补充信息仅用于本次政策匹配，正式企业画像未更新');return}
    var source=profileSnapshotV84.row||{},task={profileReviewTaskV84:true,reviewId:'ENT-PROFILE-'+Date.now(),title:profileSnapshotV84.name,sub:'企业画像更新审核任务 · '+profileSnapshotV84.fields.length+' 个字段待核验',code:profileSnapshotV84.code,category:source.category||'新能源汽车',level:source.level||'市级',region:source.region||'江苏省 / 海州市',capital:source.capital||'待核验',honor:source.honor||'待核验',date:'2026-08-24',reviewStatus:'pending',status:'待审核',submitter:'政策服务人员 · 李敏',department:'海州市工业和信息化局 · 企业服务处',submitTime:'2026-08-24 18:30',targetCode:profileSnapshotV84.code,fields:profileSnapshotV84.fields,proofs:profileSnapshotV84.proofs,subjectCheck:'企业名称与统一社会信用代码一致',formatCheck:'已完成字段格式与数值范围预校验',publicDataCheck:'待与政府公示、采购及数据厂商信息比对',timeliness:'本次填报数据口径：上年度 / 当前',conflictSummary:profileSnapshotV84.fields.filter(function(field){return field.conflict}).length+' 个字段存在冲突或重点复核提示',historyPolicy:'历史政策匹配报告保持原版本，不直接修改'};knowledgeBaseConfigs.company.rows.unshift(task);profileTaskIndexV84=0;if(banner)banner.querySelector('em').textContent='画像更新申请 · 待审核';notify('已生成企业画像更新审核任务，可前往企业库按字段审核');
  };
  var previousOpenProfile=window.openEnterpriseProfile;window.openEnterpriseProfile=function(){mountProfileFlow();fillProfileForm();return previousOpenProfile.apply(this,arguments)};
  function enhanceCompanyTaskTable(){
    if(typeof activeKnowledgeType==='undefined'||activeKnowledgeType!=='company')return;var head=document.querySelector('#kbTableHead tr'),body=document.getElementById('kbTableBody');if(!head||!body)return;if(!head.querySelector('.company-review-head-v84')){var submitter=document.createElement('th');submitter.className='company-review-head-v84';submitter.textContent='提交人';head.insertBefore(submitter,head.lastElementChild);var status=document.createElement('th');status.className='company-review-head-v84';status.textContent='画像审核状态';head.insertBefore(status,head.lastElementChild)}
    Array.from(body.querySelectorAll('tr')).forEach(function(tr,position){var item=activeKnowledgeRows[position];if(!item)return;var row=item.row,action=tr.lastElementChild,submitter=document.createElement('td'),status=document.createElement('td');submitter.innerHTML=row.profileReviewTaskV84?'<b>'+esc(row.submitter)+'</b><small>'+esc(row.submitTime)+'</small>':'<span>企业主数据</span>';status.innerHTML=row.profileReviewTaskV84?'<em class="company-review-badge-v84 '+row.reviewStatus+'">'+(row.reviewStatus==='pending'?'待字段审核':row.reviewStatus==='approved'?'已正式入库':row.reviewStatus==='partial'?'部分通过':'已驳回')+'</em>':'<em class="company-review-badge-v84 approved">正式画像</em>';tr.insertBefore(submitter,action);tr.insertBefore(status,action);if(row.profileReviewTaskV84){tr.classList.add('company-profile-task-row-v84');action.innerHTML='<button class="kb-row-action" onclick="event.stopPropagation();openKnowledgeDetail('+item.index+')">查看审核任务 →</button>'}}
    );
  }
  function renderCompanyReviewTask(row,index){
    profileTaskIndexV84=index;document.getElementById('kbDetailType').textContent='企业库 · 企业画像更新审核任务';document.getElementById('kbDetailTitle').textContent=row.title;document.getElementById('kbDetailMeta').textContent='任务 '+row.reviewId+' · '+row.submitter+' · '+row.submitTime;
    var rows=row.fields.map(function(field,i){return '<tr><td><b>'+esc(field.label)+'</b><small>'+esc(field.key)+'</small></td><td>'+esc(field.oldValue)+'</td><td>'+esc(field.newValue)+'</td><td>'+esc(field.proof)+'</td><td>'+(field.conflict?'<em class="field-conflict-v84">'+esc(field.conflict)+'</em>':'<span class="field-normal-v84">未发现异常</span>')+'</td><td><select data-profile-field-review="'+i+'"><option value="pending" '+(field.status==='pending'?'selected':'')+'>待审核</option><option value="approved" '+(field.status==='approved'?'selected':'')+'>通过</option><option value="rejected" '+(field.status==='rejected'?'selected':'')+'>驳回</option><option value="conflict" '+(field.status==='conflict'?'selected':'')+'>冲突待核验</option></select></td></tr>'}).join('');
    document.getElementById('kbDetailBody').innerHTML='<section class="company-task-overview-v84"><div><span>企业主体</span><b>'+esc(row.title)+'</b><em>'+esc(row.code)+'</em></div><div><span>提交人及部门</span><b>'+esc(row.submitter)+'</b><em>'+esc(row.department)+'</em></div><div><span>任务状态</span><b>待字段级审核</b><em>'+row.fields.length+' 个字段</em></div><div><span>冲突检测</span><b>'+esc(row.conflictSummary)+'</b><em>禁止自动覆盖已审核值</em></div></section><section class="company-review-checks-v84"><b>审核核验清单</b><span>① '+esc(row.subjectCheck)+'</span><span>② '+esc(row.formatCheck)+'</span><span>③ 与企业库现有数据比较</span><span>④ '+esc(row.publicDataCheck)+'</span><span>⑤ 证明材料核验</span><span>⑥ '+esc(row.timeliness)+'</span><span>⑦ 冲突数据人工处理</span></section><section class="kb-detail-section"><h3>字段变更前后对比与审核结论</h3><div class="company-field-review-wrap-v84"><table><thead><tr><th>字段</th><th>企业库当前值</th><th>用户提交值</th><th>证明材料</th><th>冲突/异常</th><th>字段审核结果</th></tr></thead><tbody>'+rows+'</tbody></table></div></section><div class="company-review-rule-v84"><b>数据冲突规则：</b>已由用户补充且审核通过的字段锁定为“人工核验值”，后续数据厂商季度更新不得直接覆盖，仅标记“有更新”并进入人工复核。正式入库会保存原值、新值、审核人、审核时间、来源和可信等级；'+esc(row.historyPolicy)+'。</div>';
    var modal=document.getElementById('kbDetailModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';mountCompanyReviewFooter(row);
  }
  function cleanDetailFooter(){var footer=document.querySelector('#kbDetailModal .kb-detail-dialog>footer'),extra=document.getElementById('detailWorkflowActionsV84'),save=footer&&footer.querySelector('button.primary');if(extra)extra.remove();if(save)save.style.display=''}
  function mountPolicyReviewFooter(index){
    cleanDetailFooter();if(typeof activeKnowledgeType==='undefined'||activeKnowledgeType!=='policy')return;var row=knowledgeBaseConfigs.policy.rows[index],footer=document.querySelector('#kbDetailModal .kb-detail-dialog>footer');if(!row||!footer||row.reviewStatus!=='pending'||!row.reviewId)return;var bodyActions=document.querySelector('#policyDetailGovernanceV83 .policy-detail-review-actions-v83');if(bodyActions)bodyActions.remove();var actions=document.createElement('div');actions.id='detailWorkflowActionsV84';actions.className='detail-workflow-actions-v84';actions.innerHTML='<button class="review-reject-v84" type="button" onclick="openPolicyAuditV78(\''+row.reviewId+'\',\'reject\')">驳回</button><button class="review-approve-v84" type="button" onclick="openPolicyAuditV78(\''+row.reviewId+'\',\'approve\')">审核通过</button>';var save=footer.querySelector('button.primary');footer.insertBefore(actions,save||null);
  }
  function mountCompanyReviewFooter(row){
    cleanDetailFooter();var footer=document.querySelector('#kbDetailModal .kb-detail-dialog>footer');if(!footer)return;var actions=document.createElement('div');actions.id='detailWorkflowActionsV84';actions.className='detail-workflow-actions-v84';actions.innerHTML='<button class="secondary" type="button" onclick="saveEnterpriseFieldReviewV84(false)">保存审核进度</button><button class="primary" type="button" onclick="saveEnterpriseFieldReviewV84(true)">完成审核并正式入库</button>';var save=footer.querySelector('button.primary');if(save)save.style.display='none';footer.appendChild(actions);
  }
  window.saveEnterpriseFieldReviewV84=function(complete){
    var task=knowledgeBaseConfigs.company.rows[profileTaskIndexV84];if(!task||!task.profileReviewTaskV84)return;document.querySelectorAll('[data-profile-field-review]').forEach(function(select){task.fields[Number(select.dataset.profileFieldReview)].status=select.value});if(!complete){task.lastSavedAt='2026-08-24 18:42';notify('字段审核进度已保存');return}
    var unresolved=task.fields.filter(function(field){return field.status==='pending'||field.status==='conflict'});if(unresolved.length){notify('仍有 '+unresolved.length+' 个字段待审核或冲突待核验，暂不能正式入库');return}var approved=task.fields.filter(function(field){return field.status==='approved'}),rejected=task.fields.filter(function(field){return field.status==='rejected'}),target=knowledgeBaseConfigs.company.rows.find(function(row){return !row.profileReviewTaskV84&&row.code===task.targetCode});if(target){target.profileData=target.profileData||{};target.fieldLocks=target.fieldLocks||{};target.profileAuditHistory=target.profileAuditHistory||[];approved.forEach(function(field){target.profileData[field.key]=field.newValue;target[field.key]=field.newValue;if(field.key==='revenue')target.revenueWan=field.newValue;target.fieldLocks[field.key]=true;target.profileAuditHistory.push({field:field.label,oldValue:field.oldValue,newValue:field.newValue,auditor:'知识库运营审核员 · 王宁',auditTime:'2026-08-24 18:48',source:'企业用户补充 + 证明材料',confidence:'人工核验 / 高'})});target.searchIndexRefreshed=true;target.vendorUpdateMode='仅标记有更新，不自动覆盖'}task.reviewStatus=rejected.length?(approved.length?'partial':'rejected'):'approved';task.status=task.reviewStatus==='approved'?'已正式入库':task.reviewStatus==='partial'?'部分字段入库':'已驳回';task.auditor='知识库运营审核员 · 王宁';task.auditTime='2026-08-24 18:48';task.resultNotice='已通知提交人';renderKnowledgeList();openKnowledgeDetail(profileTaskIndexV84);notify('字段审核已完成：通过 '+approved.length+' 项，驳回 '+rejected.length+' 项；企业检索与画像索引已刷新');
  };
  var previousRender=window.renderKnowledgeList;window.renderKnowledgeList=function(){var result=previousRender.apply(this,arguments);enhanceCompanyTaskTable();return result};
  var previousDetail=window.openKnowledgeDetail;window.openKnowledgeDetail=function(index){cleanDetailFooter();if(typeof activeKnowledgeType!=='undefined'&&activeKnowledgeType==='company'){var row=knowledgeBaseConfigs.company.rows[index];if(row&&row.profileReviewTaskV84){renderCompanyReviewTask(row,index);return}}var result=previousDetail.apply(this,arguments);mountPolicyReviewFooter(index);return result};
  mountProfileFlow();
  if(typeof prototypeLogicAnnotations!=='undefined'){prototypeLogicAnnotations.enterprisePolicy.interactions.push(['企业画像补充与更新申请','选择企业并完善缺失字段，提交后先用补充数据重新匹配政策。','点击确定并更新匹配结果后，保存补充信息快照并直接刷新当前政策匹配结果。']);prototypeLogicAnnotations.knowledgeList.interactions.push(['企业画像字段级审核','企业库打开画像更新审核任务。','逐字段比对原值与提交值，核验证明材料、格式、时效性和冲突；仅通过字段正式入库并锁定为人工核验值，厂商新数据只提示“有更新”。'])}
})();
