(function(){
  'use strict';
  var proofTaskIndexV85=null;
  function notify(text){if(typeof window.toast==='function')window.toast(text)}
  function esc(value){return String(value==null?'':value).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
  function mountProfileActions(){
    var modal=document.getElementById('profileModal'),footer=modal&&modal.querySelector('.profile-modal>footer');if(!footer)return;
    var other=document.getElementById('profileOtherPolicyInfoV84');if(other){var label=other.closest('label');if(label)label.remove()}
    var extra=modal.querySelector('.profile-extra-v84');if(extra)extra.classList.add('proof-only-v85');
    footer.innerHTML='<p>补充信息将先用于重新计算本次政策匹配结果，请选择是否同步申请更新企业库正式画像</p><button class="secondary" type="button" onclick="closeEnterpriseProfile()">取消</button><button class="secondary profile-once-v85" type="button" onclick="submitEnterpriseProfileV85(false)">仅本次匹配使用</button><button class="primary" type="button" onclick="submitEnterpriseProfileV85(true)">本次使用并更新企业库画像</button>';
  }
  window.submitEnterpriseProfileV85=function(apply){
    var industry=document.getElementById('profileIndustry'),revenue=document.getElementById('profileRevenue');if(!industry||!industry.value){notify('请选择所属行业');if(industry)industry.focus();return}if(!revenue||!revenue.value){notify('请选择上年度营业收入');if(revenue)revenue.focus();return}
    window.saveEnterpriseProfile();setTimeout(function(){window.useProfileSnapshotV84(apply)},360);
  };
  var previousUse=window.useProfileSnapshotV84;
  if(typeof previousUse==='function')window.useProfileSnapshotV84=function(apply){var result=previousUse.apply(this,arguments);if(apply&&typeof knowledgeBaseConfigs!=='undefined'){var task=knowledgeBaseConfigs.company.rows.find(function(row){return row.profileReviewTaskV84&&row.reviewStatus==='pending'});if(task){task.fields=task.fields.filter(function(field){return field.key!=='otherInfo'});task.sub='企业画像更新审核任务 · '+task.fields.length+' 个字段待核验';task.conflictSummary=task.fields.filter(function(field){return field.conflict}).length+' 个字段存在冲突或重点复核提示'}}var banner=document.getElementById('enterpriseProfileSnapshotV84'),span=banner&&banner.querySelector('span');if(span)span.textContent=span.textContent.replace(/\d+ 个企业画像字段/,document.querySelectorAll('#profileModal [id^="profile"]').length?'14 个企业画像字段':'14 个企业画像字段');return result};
  function mountCompanyAuditFilter(){
    var category=document.getElementById('kbCategoryFilter');if(!category)return;var select=document.getElementById('kbCompanyAuditFilterV85');if(!select){select=document.createElement('select');select.id='kbCompanyAuditFilterV85';select.innerHTML='<option value="all">全部审核状态</option><option value="pending">待审核</option><option value="approved">已通过</option><option value="partial">部分通过</option><option value="rejected">已驳回</option>';select.onchange=function(){renderKnowledgeList()};category.insertAdjacentElement('afterend',select)}select.style.display=typeof activeKnowledgeType!=='undefined'&&activeKnowledgeType==='company'?'':'none';
  }
  function applyCompanyAuditFilter(){
    mountCompanyAuditFilter();if(typeof activeKnowledgeType==='undefined'||activeKnowledgeType!=='company')return;var filter=document.getElementById('kbCompanyAuditFilterV85'),body=document.getElementById('kbTableBody');if(!filter||!body)return;var shown=0;
    Array.from(body.querySelectorAll('tr')).forEach(function(tr,position){var item=activeKnowledgeRows[position];if(!item)return;var row=item.row,state=row.profileReviewTaskV84?row.reviewStatus:'formal',badge=tr.querySelector('.company-review-badge-v84');if(badge&&state==='pending')badge.textContent='待审核';if(filter.value!=='all'&&state!==filter.value){tr.remove();return}shown++});
    if(!shown)body.innerHTML='<tr><td colspan="10"><div class="kb-empty"><b>暂无符合审核状态的数据</b><span>请调整审核状态筛选后重新查看</span></div></td></tr>';var count=document.getElementById('kbResultCount');if(count)count.textContent='共 '+shown+' 条数据 · 已展示第 1 页';
  }
  function mountProofModal(){
    if(document.getElementById('enterpriseProofPreviewV85'))return;document.body.insertAdjacentHTML('beforeend','<div class="prototype-modal-backdrop enterprise-proof-backdrop-v85" id="enterpriseProofPreviewV85" aria-hidden="true"><section class="prototype-modal enterprise-proof-dialog-v85"><header><div><label>SUPPORTING MATERIAL PREVIEW</label><h2 id="enterpriseProofTitleV85">证明材料预览</h2><p id="enterpriseProofMetaV85">企业画像字段审核依据</p></div><button type="button" onclick="closeEnterpriseProofV85()">×</button></header><div class="prototype-modal-body"><div class="enterprise-proof-file-v85"><i>文</i><div><b id="enterpriseProofFileV85"></b><span>已完成文件安全扫描与内容识别</span></div><em>可预览</em></div><div class="enterprise-proof-page-v85"><header><span>材料内容预览</span><b id="enterpriseProofFieldV85"></b></header><section><h3>企业数据证明材料</h3><p id="enterpriseProofTextV85"></p><div><span>企业名称：海州智造科技有限公司</span><span>数据期间：2025年度 / 当前</span><span>材料来源：企业用户提交</span><span>校验状态：等待审核员核验</span></div></section></div></div><footer><button class="secondary" type="button" onclick="closeEnterpriseProofV85()">关闭预览</button><button class="primary" type="button" onclick="closeEnterpriseProofV85();notifyProofReviewedV85()">标记已核验</button></footer></section></div>');
  }
  window.previewEnterpriseProofV85=function(taskIndex,fieldIndex){var task=knowledgeBaseConfigs.company.rows[taskIndex],field=task&&task.fields[fieldIndex];if(!field)return;proofTaskIndexV85=taskIndex;mountProofModal();document.getElementById('enterpriseProofTitleV85').textContent=field.label+' · 证明材料';document.getElementById('enterpriseProofMetaV85').textContent=task.title+' · 字段变更审核';document.getElementById('enterpriseProofFileV85').textContent=field.proof;document.getElementById('enterpriseProofFieldV85').textContent=field.label;document.getElementById('enterpriseProofTextV85').textContent=field.proof.indexOf('待补充')>-1?'当前为用户填报承诺说明，正式审核前建议补充可验证的财务报表、纳税证明、研发台账或项目备案材料。':'系统已识别材料中的企业主体、数据期间及字段数值，请与用户提交值和企业库现值进行人工比对。';var modal=document.getElementById('enterpriseProofPreviewV85');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
  window.closeEnterpriseProofV85=function(){var modal=document.getElementById('enterpriseProofPreviewV85');if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''};
  window.notifyProofReviewedV85=function(){notify('证明材料已标记为人工核验')};
  function enhanceCompanyReviewDetail(index){
    if(typeof activeKnowledgeType==='undefined'||activeKnowledgeType!=='company')return;var task=knowledgeBaseConfigs.company.rows[index];if(!task||!task.profileReviewTaskV84)return;var status=document.querySelector('.company-task-overview-v84>div:nth-child(3) b');if(status&&task.reviewStatus==='pending')status.textContent='待审核';document.querySelectorAll('.company-field-review-wrap-v84 tbody tr').forEach(function(tr,fieldIndex){var cell=tr.children[3],field=task.fields[fieldIndex];if(cell&&field)cell.innerHTML='<button class="proof-preview-btn-v85" type="button" onclick="previewEnterpriseProofV85('+index+','+fieldIndex+')"><i>▤</i><span>'+esc(field.proof)+'</span><em>预览</em></button>'});var saveProgress=Array.from(document.querySelectorAll('#detailWorkflowActionsV84 button')).find(function(button){return button.getAttribute('onclick')&&button.getAttribute('onclick').indexOf('saveEnterpriseFieldReviewV84(false)')>-1});if(saveProgress)saveProgress.textContent='保存';
  }
  var previousOpenKnowledge=window.openKnowledgeBase;if(typeof previousOpenKnowledge==='function')window.openKnowledgeBase=function(type){var result=previousOpenKnowledge.apply(this,arguments);mountCompanyAuditFilter();return result};
  var previousRender=window.renderKnowledgeList;if(typeof previousRender==='function')window.renderKnowledgeList=function(){var result=previousRender.apply(this,arguments);applyCompanyAuditFilter();return result};
  var previousDetail=window.openKnowledgeDetail;if(typeof previousDetail==='function')window.openKnowledgeDetail=function(index){var result=previousDetail.apply(this,arguments);enhanceCompanyReviewDetail(index);return result};
  mountProfileActions();mountCompanyAuditFilter();mountProofModal();
  if(typeof prototypeLogicAnnotations!=='undefined'){prototypeLogicAnnotations.enterprisePolicy.interactions.push(['画像信息一次提交','在完善企业信息弹窗底部直接选择使用方式。','选择仅本次匹配或本次使用并更新企业库画像，不再二次弹窗确认；证明材料随画像更新审核任务保存。']);prototypeLogicAnnotations.knowledgeList.interactions.push(['企业画像审核记录筛选与材料预览','进入企业库选择审核状态并查看画像更新任务。','待审核任务统一显示“待审核”；证明材料可点击预览，审核进度使用“保存”按钮暂存。'])}
})();
