(function(){
  'use strict';
  var filterV88='all';
  var messagesV88=[
    {id:1,type:'approved',library:'企业库',title:'企业画像更新审核通过',body:'海州智造科技有限公司的 12 个画像字段已通过审核并更新正式企业库。',time:'今天 10:26',read:false,target:'company'},
    {id:2,type:'rejected',library:'政策库',title:'政策入库申请已驳回',body:'《海州市工业软件应用示范项目申报通知》缺少正式发文编号，请补充后重新提交。',time:'今天 09:48',read:false,target:'policy'},
    {id:3,type:'approved',library:'政策库',title:'政策数据审核通过',body:'《制造业数字化转型专项资金申报通知》已完成审核并正式入库。',time:'昨天 17:32',read:true,target:'policy'},
    {id:4,type:'rejected',library:'企业库',title:'企业画像字段审核驳回',body:'芯源微电子科技股份有限公司的上年度营收数据与证明材料口径不一致。',time:'昨天 15:16',read:true,target:'company'}
  ];
  function esc(value){return String(value==null?'':value).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
  function mountMessageCenter(){
    if(document.getElementById('messageCenterLauncherV88'))return;var user=document.querySelector('.side-user');if(!user)return;
    user.insertAdjacentHTML('beforebegin','<button class="message-center-launcher-v88" id="messageCenterLauncherV88" type="button" onclick="toggleMessageCenterV88()"><i>✉</i><span>消息中心</span><em id="messageUnreadV88">2</em></button>');
    document.body.insertAdjacentHTML('beforeend','<aside class="message-center-drawer-v88" id="messageCenterDrawerV88" aria-hidden="true"><header><div><label>NOTIFICATION CENTER</label><h2>消息中心</h2><p>接收政策、企业及其他数据审核结果</p></div><button type="button" onclick="toggleMessageCenterV88(false)">×</button></header><nav><button class="active" data-message-filter-v88="all" onclick="setMessageFilterV88(\'all\',this)">全部</button><button data-message-filter-v88="unread" onclick="setMessageFilterV88(\'unread\',this)">未读</button><button data-message-filter-v88="approved" onclick="setMessageFilterV88(\'approved\',this)">审核通过</button><button data-message-filter-v88="rejected" onclick="setMessageFilterV88(\'rejected\',this)">审核驳回</button></nav><div class="message-list-v88" id="messageListV88"></div><footer><span id="messageSummaryV88"></span><button type="button" onclick="markAllMessagesReadV88()">全部标为已读</button></footer></aside>');renderMessagesV88();
  }
  function renderMessagesV88(){
    var list=document.getElementById('messageListV88');if(!list)return;var rows=messagesV88.filter(function(item){return filterV88==='all'||(filterV88==='unread'?!item.read:item.type===filterV88)});
    list.innerHTML=rows.length?rows.map(function(item){return '<article class="message-item-v88 '+item.type+' '+(item.read?'read':'unread')+'" onclick="openReviewMessageV88('+item.id+')"><i>'+(item.type==='approved'?'✓':'!')+'</i><div><header><b>'+esc(item.title)+'</b><time>'+esc(item.time)+'</time></header><p>'+esc(item.body)+'</p><footer><span>'+esc(item.library)+'</span><em>查看数据 →</em></footer></div></article>'}).join(''):'<div class="message-empty-v88"><i>✓</i><b>暂无相关消息</b><span>新的数据审核结果会显示在这里</span></div>';
    var unread=messagesV88.filter(function(item){return !item.read}).length,badge=document.getElementById('messageUnreadV88'),summary=document.getElementById('messageSummaryV88');if(badge){badge.textContent=unread;badge.style.display=unread?'grid':'none'}if(summary)summary.textContent='共 '+messagesV88.length+' 条 · '+unread+' 条未读';
  }
  window.toggleMessageCenterV88=function(open){var drawer=document.getElementById('messageCenterDrawerV88');if(!drawer)return;var next=typeof open==='boolean'?open:!drawer.classList.contains('open');drawer.classList.toggle('open',next);drawer.setAttribute('aria-hidden',String(!next));var launcher=document.getElementById('messageCenterLauncherV88');if(launcher)launcher.classList.toggle('active',next)};
  window.setMessageFilterV88=function(filter,button){filterV88=filter;document.querySelectorAll('[data-message-filter-v88]').forEach(function(item){item.classList.toggle('active',item===button)});renderMessagesV88()};
  window.markAllMessagesReadV88=function(){messagesV88.forEach(function(item){item.read=true});renderMessagesV88();if(typeof window.toast==='function')window.toast('全部消息已标记为已读')};
  window.openReviewMessageV88=function(id){var message=messagesV88.find(function(item){return item.id===id});if(!message)return;message.read=true;renderMessagesV88();toggleMessageCenterV88(false);if(typeof window.openKnowledgeBase==='function')window.openKnowledgeBase(message.target)};
  window.pushReviewMessageV88=function(type,library,title,body,target){messagesV88.unshift({id:Date.now(),type:type,library:library,title:title,body:body,time:'刚刚',read:false,target:target});renderMessagesV88()};
  var legacyPolicyConfirm=window.confirmPolicyAuditV78;if(typeof legacyPolicyConfirm==='function')window.confirmPolicyAuditV78=function(){var before=(knowledgeBaseConfigs.policy.rows||[]).map(function(row){return {id:row.reviewId,status:row.reviewStatus}}),result=legacyPolicyConfirm.apply(this,arguments);(knowledgeBaseConfigs.policy.rows||[]).forEach(function(row){var old=before.find(function(item){return item.id&&item.id===row.reviewId});if(old&&old.status==='pending'&&row.reviewStatus!==old.status)pushReviewMessageV88(row.reviewStatus==='approved'?'approved':'rejected','政策库',row.reviewStatus==='approved'?'政策数据审核通过':'政策入库申请已驳回','《'+row.title+'》'+(row.reviewStatus==='approved'?'已通过审核并正式入库。':'未通过审核，请根据审核意见补充或修订。'),'policy')});return result};
  var legacyEnterpriseSave=window.saveEnterpriseFieldReviewV84;if(typeof legacyEnterpriseSave==='function')window.saveEnterpriseFieldReviewV84=function(complete){var before=(knowledgeBaseConfigs.company.rows||[]).map(function(row){return {id:row.reviewId,status:row.reviewStatus}}),result=legacyEnterpriseSave.apply(this,arguments);if(complete)(knowledgeBaseConfigs.company.rows||[]).forEach(function(row){var old=before.find(function(item){return item.id&&item.id===row.reviewId});if(old&&old.status==='pending'&&row.reviewStatus!==old.status){var approved=row.reviewStatus==='approved'||row.reviewStatus==='partial';pushReviewMessageV88(approved?'approved':'rejected','企业库',approved?'企业画像更新审核完成':'企业画像更新审核驳回',row.title+'的画像字段审核已完成，结果：'+row.status+'。','company')}});return result};
  mountMessageCenter();
  if(typeof prototypeLogicAnnotations!=='undefined')prototypeLogicAnnotations.system.interactions.push(['审核消息通知','政策或企业数据完成审核后，左下角消息中心显示未读提醒。','消息区分审核通过与审核驳回；点击消息标记已读并进入对应知识库，支持按状态筛选和全部已读。']);
})();
