(function(){
  'use strict';
  var taskIndexV90=null,projectIndexV90=null;
  function esc(value){return String(value==null?'':value).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
  function notify(text){if(typeof window.toast==='function')window.toast(text)}
  function openModal(id){var modal=document.getElementById(id);if(!modal)return;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
  function closeModal(id){var modal=document.getElementById(id);if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');if(!document.querySelector('#kbDetailModal.open'))document.body.style.overflow=''}
  function mountPolicyTaskModals(){
    if(!document.getElementById('similarPolicyDetailV90'))document.body.insertAdjacentHTML('beforeend','<div class="prototype-modal-backdrop" id="similarPolicyDetailV90" aria-hidden="true"><section class="prototype-modal similar-policy-dialog-v90"><header><div><label>SIMILAR POLICY DETAIL</label><h2 id="similarPolicyTitleV90">相似政策详情</h2><p id="similarPolicyMetaV90"></p></div><button type="button" onclick="closeSimilarPolicyV90()">×</button></header><div class="prototype-modal-body"><div class="similar-policy-score-v90"><div><span>文本语义相似度</span><b id="similarPolicyScoreV90">--</b></div><p id="similarPolicyResultV90"></p></div><section class="similar-policy-content-v90"><h3>政策内容摘要</h3><p id="similarPolicyAbstractV90"></p><dl><div><dt>发文机构</dt><dd id="similarPolicyOrgV90"></dd></div><div><dt>发布时间</dt><dd id="similarPolicyDateV90"></dd></div><div><dt>文件关系判断</dt><dd id="similarPolicyRelationV90"></dd></div><div><dt>审核建议</dt><dd>核对发文编号、有效期、项目条件及原文附件后，选择新建、合并或关联入库。</dd></div></dl></section></div><footer><button class="secondary" type="button" onclick="closeSimilarPolicyV90()">关闭</button><button class="primary" type="button" onclick="notifySimilarComparedV90()">标记已核对</button></footer></section></div>');
    if(!document.getElementById('policyProjectEditV90'))document.body.insertAdjacentHTML('beforeend','<div class="prototype-modal-backdrop" id="policyProjectEditV90" aria-hidden="true"><section class="prototype-modal policy-project-edit-dialog-v90"><header><div><label>POLICY PROJECT EDITOR</label><h2>编辑解析政策项目</h2><p>修改内容将写回当前政策入库审核任务，审核通过后进入正式项目库。</p></div><button type="button" onclick="closePolicyProjectEditV90()">×</button></header><div class="prototype-modal-body"><div class="policy-project-form-v90"><label class="wide"><span>项目名称</span><input id="projectNameV90"></label><label><span>项目分类</span><select id="projectCategoryV90"><option>固定资产投入补贴</option><option>企业荣誉资质奖励</option><option>企业管理提升奖励</option><option>融资贷款补贴</option><option>人才补贴</option><option>税收优惠</option><option>其他补贴</option></select></label><label><span>最高补贴金额</span><input id="projectAmountV90"></label><label class="wide"><span>申报条件</span><textarea id="projectConditionV90"></textarea></label><label class="wide"><span>补贴政策</span><textarea id="projectSubsidyV90"></textarea></label><label><span>申报时间</span><input id="projectApplyTimeV90"></label><label><span>申报截止</span><input id="projectDeadlineV90"></label></div></div><footer><button class="secondary" type="button" onclick="closePolicyProjectEditV90()">取消</button><button class="primary" type="button" onclick="savePolicyProjectV90()">保存项目修改</button></footer></section></div>');
  }
  function currentTask(){return typeof knowledgeBaseConfigs!=='undefined'&&taskIndexV90!=null?knowledgeBaseConfigs.policy.rows[taskIndexV90]:null}
  function enhanceSimilarPolicies(row,index){
    var table=document.querySelector('#kbDetailBody .similar-policy-table-v80');if(!table||table.classList.contains('interactive-v90'))return;table.classList.add('interactive-v90');var head=table.querySelector('thead tr');if(head)head.insertAdjacentHTML('beforeend','<th>操作</th>');Array.from(table.querySelectorAll('tbody tr')).forEach(function(tr,similarIndex){tr.tabIndex=0;tr.setAttribute('role','button');tr.setAttribute('aria-label','查看相似政策详情');tr.onclick=function(){openSimilarPolicyV90(index,similarIndex)};tr.onkeydown=function(event){if(event.key==='Enter'||event.key===' '){event.preventDefault();openSimilarPolicyV90(index,similarIndex)}};tr.insertAdjacentHTML('beforeend','<td><button class="similar-detail-btn-v90" type="button">查看详情 →</button></td>')});
  }
  function projectCards(row,index){var editable=row.reviewStatus==='pending';return (row.projects||[]).map(function(project,projectIndex){if(project.matchEnabled==null)project.matchEnabled=!!project.selected;return '<article class="policy-project-manage-v90 '+(project.matchEnabled?'match-on':'')+'"><header><div><h4>'+esc(project.name)+'</h4><span>项目 '+String(projectIndex+1).padStart(2,'0')+' · '+esc(project.category)+'</span></div><div class="policy-project-actions-v90"><label>参与匹配</label><button class="project-match-switch-v90 '+(project.matchEnabled?'on':'')+'" type="button" '+(editable?'onclick="togglePolicyProjectMatchV90('+index+','+projectIndex+')"':'disabled')+' aria-pressed="'+String(project.matchEnabled)+'"><i></i></button>'+(editable?'<button class="edit" type="button" onclick="openPolicyProjectEditV90('+index+','+projectIndex+')">编辑</button><button class="delete" type="button" onclick="deletePolicyProjectV90('+index+','+projectIndex+')">删除</button>':'')+'</div></header><dl><div><dt>最高补贴</dt><dd>'+esc(project.amount)+'</dd></div><div><dt>申报时间</dt><dd>'+esc(project.applyTime)+'</dd></div><div class="wide"><dt>申报条件</dt><dd>'+esc(project.condition)+'</dd></div><div class="wide"><dt>补贴政策</dt><dd>'+esc(project.subsidy)+'</dd></div></dl></article>'}).join('')}
  function enhanceProjectManagement(row,index){var container=document.querySelector('#kbDetailBody .uploaded-project-detail-v79');if(!container)return;container.classList.add('policy-project-management-v90');container.innerHTML=projectCards(row,index);var title=container.closest('.kb-detail-section')&&container.closest('.kb-detail-section').querySelector('h3');if(title)title.innerHTML='拆解出的政策项目 <span class="project-count-v90">共 '+(row.projects||[]).length+' 项</span>'}
  function enhancePolicyAuditTask(index){if(typeof activeKnowledgeType==='undefined'||activeKnowledgeType!=='policy'||typeof knowledgeBaseConfigs==='undefined')return;var row=knowledgeBaseConfigs.policy.rows[index];if(!row||!row.auditTaskV80)return;taskIndexV90=index;enhanceProjectManagement(row,index);enhanceSimilarPolicies(row,index)}
  window.openSimilarPolicyV90=function(index,similarIndex){var row=knowledgeBaseConfigs.policy.rows[index],policy=row&&row.similarPolicies&&row.similarPolicies[similarIndex];if(!policy)return;taskIndexV90=index;mountPolicyTaskModals();document.getElementById('similarPolicyTitleV90').textContent=policy.title;document.getElementById('similarPolicyMetaV90').textContent='相似政策 '+String(similarIndex+1).padStart(2,'0')+' · '+row.title;document.getElementById('similarPolicyScoreV90').textContent=policy.similarity;document.getElementById('similarPolicyResultV90').textContent=policy.result;document.getElementById('similarPolicyOrgV90').textContent=policy.org;document.getElementById('similarPolicyDateV90').textContent=policy.date;document.getElementById('similarPolicyRelationV90').textContent=Number(String(policy.similarity).replace('%',''))>=80?'疑似同主题或重复政策':Number(String(policy.similarity).replace('%',''))>=65?'存在部分项目与条件重合':'上位依据或关联政策，重复风险较低';document.getElementById('similarPolicyAbstractV90').textContent='该文件围绕制造业数字化改造、智能工厂建设及专项资金申报提出支持范围、申报主体、补助标准和材料要求。系统已完成标题、正文、申报条件和补贴条款的语义比对，建议结合正式发文编号与有效期进行人工复核。';openModal('similarPolicyDetailV90')};
  window.closeSimilarPolicyV90=function(){closeModal('similarPolicyDetailV90')};window.notifySimilarComparedV90=function(){closeSimilarPolicyV90();notify('已标记该相似政策为人工核对')};
  window.openPolicyProjectEditV90=function(index,projectIndex){var row=knowledgeBaseConfigs.policy.rows[index],project=row&&row.projects&&row.projects[projectIndex];if(!project)return;taskIndexV90=index;projectIndexV90=projectIndex;mountPolicyTaskModals();document.getElementById('projectNameV90').value=project.name||'';document.getElementById('projectCategoryV90').value=project.category||'其他补贴';document.getElementById('projectAmountV90').value=project.amount||'';document.getElementById('projectConditionV90').value=project.condition||'';document.getElementById('projectSubsidyV90').value=project.subsidy||'';document.getElementById('projectApplyTimeV90').value=project.applyTime||'';document.getElementById('projectDeadlineV90').value=project.deadline||'';openModal('policyProjectEditV90')};
  window.closePolicyProjectEditV90=function(){closeModal('policyProjectEditV90')};
  window.savePolicyProjectV90=function(){var row=currentTask(),project=row&&row.projects&&row.projects[projectIndexV90];if(!project)return;var name=document.getElementById('projectNameV90').value.trim();if(!name){notify('请输入项目名称');return}project.name=name;project.category=document.getElementById('projectCategoryV90').value;project.amount=document.getElementById('projectAmountV90').value.trim();project.condition=document.getElementById('projectConditionV90').value.trim();project.subsidy=document.getElementById('projectSubsidyV90').value.trim();project.applyTime=document.getElementById('projectApplyTimeV90').value.trim();project.deadline=document.getElementById('projectDeadlineV90').value.trim();row.userModifiedFields=row.userModifiedFields||[];if(row.userModifiedFields.indexOf('拆解政策项目（审核员修改）')<0)row.userModifiedFields.push('拆解政策项目（审核员修改）');closePolicyProjectEditV90();window.openKnowledgeDetail(taskIndexV90);notify('政策项目修改已保存到审核任务')};
  window.deletePolicyProjectV90=function(index,projectIndex){var row=knowledgeBaseConfigs.policy.rows[index];if(!row||!row.projects)return;if(row.projects.length<=1){notify('审核任务至少保留 1 个政策项目');return}var project=row.projects[projectIndex];if(!window.confirm('确定删除“'+project.name+'”吗？删除后不可在本审核任务中恢复。'))return;row.projects.splice(projectIndex,1);if(!row.projects.some(function(item){return item.selected}))row.projects[0].selected=true;window.openKnowledgeDetail(index);notify('政策项目已从审核任务中删除')};
  window.togglePolicyProjectMatchV90=function(index,projectIndex){var row=knowledgeBaseConfigs.policy.rows[index],project=row&&row.projects&&row.projects[projectIndex];if(!project)return;project.matchEnabled=!project.matchEnabled;window.openKnowledgeDetail(index);notify(project.matchEnabled?'已打开“'+project.name+'”参与匹配':'已关闭“'+project.name+'”参与匹配')};
  var legacyOpenDetail=window.openKnowledgeDetail;if(typeof legacyOpenDetail==='function')window.openKnowledgeDetail=function(index){var result=legacyOpenDetail.apply(this,arguments);enhancePolicyAuditTask(index);return result};
  mountPolicyTaskModals();
  if(typeof prototypeLogicAnnotations!=='undefined')prototypeLogicAnnotations.knowledgeList.interactions.push(['政策审核任务明细操作','进入待审核政策任务，查看拆解项目及相似政策检测。','相似政策可逐条查看详情并标记核对；拆解项目可编辑、删除和打开/关闭参与匹配，所有修改写回当前审核任务后再执行通过或驳回。']);
})();
